import { TranslationDict, FAQItem, LanguageCode } from './types';

export const translations: Record<LanguageCode, TranslationDict> = {
  en: {
    title: 'Precise Age Calculator',
    subtitle: 'High precision age, exact breakdown & premium statistics',
    birthDateLabel: 'Date of Birth',
    birthTimeLabel: 'Time of Birth (Optional)',
    calculateBtn: 'Calculate Precise Age',
    voiceBtnLabel: 'Voice Input DOB',
    voiceListening: 'Listening for Date of Birth... (e.g. "October twenty-first nineteen ninety-five")',
    voiceProcessing: 'Parsing spoke date text...',
    voiceError: 'Could not catch date clearly. Try saying "Month Day Year".',
    voiceSuccess: 'Successfully loaded date from voice command!',
    voiceStopBtn: 'Stop Listening',
    themeToggle: 'Toggle Theme',
    languageSelect: 'Choose Language',
    years: 'Years',
    months: 'Months',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    weeks: 'Weeks',
    nextBirthday: 'Next Birthday',
    birthdayCountdown: 'Days left until your special day!',
    nextBirthdayDay: 'Falls on',
    ageCategory: 'Life Category',
    child: 'Child',
    boy: 'Youth',
    teenage: 'Teenager',
    adult: 'Adult',
    senior: 'Golden Citizen',
    statsTitle: 'Chronological Insights & Statistics',
    faqTitle: 'Frequently Asked Questions (FAQ)',
    seoDescription: 'Calculate your precise age down to the second. Find your life category avatar and countdown to the next birthday.',
    adsTitle: 'Sponsored Ad Placement',
    adsSub: 'Supports free global accessibility tools',
    adsPlaceholder: 'Google AdSense Sandbox Block - Code ID: ca-pub-99824681',
    genderMale: 'Boy Avatar',
    genderFemale: 'Girl Avatar',
    genderNeutral: 'Neutral Avatar',
    genderSelect: 'Choose Avatar Perspective',
    dobPlaceholder: 'Select your birth date',
    analyticsTitle: 'Live Calculator Engagement Platform',
    analyticsSubtitle: 'Global usage trends over the last 24 hours',
    analyticsActiveUsers: 'Active Calculators Right Now',
    analyticsTotalCalc: 'Global App Usage Index',
    analyticsVoiceSuccessRate: 'Voice Parser Accuracy Rate'
  },
  es: {
    title: 'Calculadora de Edad Precisa',
    subtitle: 'Cálculo de edad de alta precisión con desglose exacto',
    birthDateLabel: 'Fecha de Nacimiento',
    birthTimeLabel: 'Hora de Nacimiento (Opcional)',
    calculateBtn: 'Calcular Edad Exacta',
    voiceBtnLabel: 'Entrada por Voz',
    voiceListening: 'Escuchando fecha... (ej: "Veintiuno de octubre de mil novecientos noventa y cinco")',
    voiceProcessing: 'Procesando texto de voz...',
    voiceError: 'No se pudo entender la fecha. Intente decir "Día Mes Año".',
    voiceSuccess: '¡Fecha cargada con éxito por voz!',
    voiceStopBtn: 'Detener de escuchar',
    themeToggle: 'Cambiar Tema',
    languageSelect: 'Elegir Idioma',
    years: 'Años',
    months: 'Meses',
    days: 'Días',
    hours: 'Horas',
    minutes: 'Minutos',
    seconds: 'Segundos',
    weeks: 'Semanas',
    nextBirthday: 'Siguiente Cumpleaños',
    birthdayCountdown: '¡Días que faltan para tu gran día!',
    nextBirthdayDay: 'Cae en',
    ageCategory: 'Categoría de Vida',
    child: 'Niño',
    boy: 'Joven',
    teenage: 'Adolescente',
    adult: 'Adulto',
    senior: 'Ciudadano Dorado',
    statsTitle: 'Estadísticas Cronológicas Detalladas',
    faqTitle: 'Preguntas Frecuentes (FAQ)',
    seoDescription: 'Calcula tu edad precisa hasta el segundo. Encuentra tu avatar de categoría de vida y la cuenta regresiva.',
    adsTitle: 'Colocación de Anuncio Patrocinado',
    adsSub: 'Soporta herramientas gratuitas accesibles en el mundo',
    adsPlaceholder: 'Bloque AdSense Sandbox - ID: ca-pub-99824681',
    genderMale: 'Avatar Chico',
    genderFemale: 'Avatar Chica',
    genderNeutral: 'Avatar Neutro',
    genderSelect: 'Elige Perspectiva de Avatar',
    dobPlaceholder: 'Selecciona tu fecha de nacimiento',
    analyticsTitle: 'Plataforma de Participación en Vivo',
    analyticsSubtitle: 'Tendencias de uso global en las últimas 24 horas',
    analyticsActiveUsers: 'Calculadoras Activas Ahora',
    analyticsTotalCalc: 'Índice de Uso Global',
    analyticsVoiceSuccessRate: 'Tasa de Éxito de Voz'
  },
  fr: {
    title: 'Calculateur d\'Âge Précis',
    subtitle: 'Âge exact en temps réel avec statistiques premium',
    birthDateLabel: 'Date de Naissance',
    birthTimeLabel: 'Heure de Naissance (Optionnel)',
    calculateBtn: 'Calculer l\'Âge Exact',
    voiceBtnLabel: 'Entrée Vocale',
    voiceListening: 'À l\'écoute... (ex: "Le premier janvier mille neuf cent quatre-vingt-dix")',
    voiceProcessing: 'Analyse de la voix...',
    voiceError: 'Date non reconnue, réessayez : "Jour Mois Année".',
    voiceSuccess: 'Date chargée par commande vocale !',
    voiceStopBtn: 'Arrêter l\'écoute',
    themeToggle: 'Changer de Thème',
    languageSelect: 'Choisir la Langue',
    years: 'Ans',
    months: 'Mois',
    days: 'Jours',
    hours: 'Heures',
    minutes: 'Minutes',
    seconds: 'Secondes',
    weeks: 'Semaines',
    nextBirthday: 'Prochain Anniversaire',
    birthdayCountdown: 'Jours restants avant votre journée spéciale !',
    nextBirthdayDay: 'Tombe un',
    ageCategory: 'Catégorie de Vie',
    child: 'Enfant',
    boy: 'Jeune',
    teenage: 'Adolescent',
    adult: 'Adulte',
    senior: 'Citoyen d\'Or',
    statsTitle: 'Statistiques Chronologiques Visuelles',
    faqTitle: 'Foire Aux Questions (FAQ)',
    seoDescription: 'Calculez votre âge précis à la seconde près. Découvrez votre avatar et le compte à rebours d\'anniversaire.',
    adsTitle: 'Emplacement Publicitaire Sponsorisé',
    adsSub: 'Prend en charge les outils d\'accessibilité mondiaux gratuits',
    adsPlaceholder: 'Sandbox Google AdSense - ID: ca-pub-99824681',
    genderMale: 'Avatar Garçon',
    genderFemale: 'Avatar Fille',
    genderNeutral: 'Avatar Neutre',
    genderSelect: 'Choisir la Perspective de l\'Avatar',
    dobPlaceholder: 'Sélectionnez votre date',
    analyticsTitle: 'Engagement de la Calculatrice en Direct',
    analyticsSubtitle: 'Tendances d\'utilisation globale ces dernières 24h',
    analyticsActiveUsers: 'Utilisateurs Actifs en Direct',
    analyticsTotalCalc: 'Index d\'Utilisation Globale',
    analyticsVoiceSuccessRate: 'Taux de Réussite Vocale'
  },
  de: {
    title: 'Präziser Altersrechner',
    subtitle: 'Hochpräzise Altersanalysen & Premium-Lebensstatistiken',
    birthDateLabel: 'Geburtsdatum',
    birthTimeLabel: 'Geburtszeit (Optional)',
    calculateBtn: 'Präzises Alter berechnen',
    voiceBtnLabel: 'Spracheingabe Geburtsdatum',
    voiceListening: 'Zuhören... (z.B. "Erster Januar neunzehnhundertneunzig")',
    voiceProcessing: 'Parsed Spracheingabe...',
    voiceError: 'Datum wurde nicht verstanden. Bitte "Tag Monat Jahr" aussprechen.',
    voiceSuccess: 'Geburtsdatum per Sprachbefehl geladen!',
    voiceStopBtn: 'Zuhören stoppen',
    themeToggle: 'Thema wechseln',
    languageSelect: 'Sprache wählen',
    years: 'Jahre',
    months: 'Monate',
    days: 'Tage',
    hours: 'Stunden',
    minutes: 'Minuten',
    seconds: 'Sekunden',
    weeks: 'Wochen',
    nextBirthday: 'Nächster Geburtstag',
    birthdayCountdown: 'Tage verbleibend bis zu Ihrem Ehrentag!',
    nextBirthdayDay: 'Fällt auf einen',
    ageCategory: 'Lebenskategorie',
    child: 'Kind',
    boy: 'Junge/Mädchen',
    teenage: 'Jugendliche(r)',
    adult: 'Erwachsene(r)',
    senior: 'Seniorenklasse',
    statsTitle: 'Chronologische Einblicke & Statistiken',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    seoDescription: 'Berechnen Sie Ihr präzises Alter sekundengenau. Finden Sie Ihr Lebensavatar und Ihren Countdown.',
    adsTitle: 'Gesponserte Platzierung',
    adsSub: 'Unterstützt die Bereitstellung barrierefreier Tools weltweit',
    adsPlaceholder: 'Google AdSense-Sandbox - ID: ca-pub-99824681',
    genderMale: 'Männliches Avatar',
    genderFemale: 'Weibliches Avatar',
    genderNeutral: 'Neutrales Avatar',
    genderSelect: 'Avatar-Stil auswählen',
    dobPlaceholder: 'Geburtsdatum auswählen',
    analyticsTitle: 'Echtzeit-Plattform-Engagement',
    analyticsSubtitle: 'Globale Nutzungstrends der letzten 24 Stunden',
    analyticsActiveUsers: 'Aktive Nutzer im Rechner',
    analyticsTotalCalc: 'Globaler Nutzungsindex',
    analyticsVoiceSuccessRate: 'Spracherkennung Genauigkeitsrate'
  },
  hi: {
    title: 'सटीक उम्र कैलकुलेटर',
    subtitle: 'उच्च सटीकता के साथ अपनी उम्र, महीने, और दिन की सटीक गणना करें',
    birthDateLabel: 'जन्म तिथि',
    birthTimeLabel: 'जन्म का समय (वैकल्पिक)',
    calculateBtn: 'सटीक आयु की गणना करें',
    voiceBtnLabel: 'आवाज से तिथि दर्ज करें',
    voiceListening: 'जन्मतिथि की आवाज सुन रहे हैं... (जैसे: "पंद्रह अगस्त उन्नीस सौ90")',
    voiceProcessing: 'आवाज का विश्लेषण कर रहे हैं...',
    voiceError: 'तिथि स्पष्ट नहीं मिली। "महीना दिन साल" बोलकर देखें।',
    voiceSuccess: 'आवाज संकेत से जन्म तिथि सफलतापूर्वक दर्ज की गई!',
    voiceStopBtn: 'सुनना बंद करें',
    themeToggle: 'थीम बदलें',
    languageSelect: 'भाषा का चयन करें',
    years: 'वर्ष',
    months: 'महीने',
    days: 'दिन',
    hours: 'घंटे',
    minutes: 'मिनट',
    seconds: 'सेकंड',
    weeks: 'सप्ताह',
    nextBirthday: 'अगला जन्मदिन',
    birthdayCountdown: 'आपके विशेष दिन के लिए बचे हुए दिन!',
    nextBirthdayDay: 'दिन पड़ता है',
    ageCategory: 'जीवन श्रेणी',
    child: 'शिशु',
    boy: 'बालक/बालिका',
    teenage: 'किशोर',
    adult: 'वयस्क',
    senior: 'वरिष्ठ नागरिक',
    statsTitle: 'कालानुक्रमिक अंतर्दृष्टि और रुझान',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न (FAQ)',
    seoDescription: 'पैक की गई सेकंड सटीकता के साथ अपनी सटीक आयु की गणना करें। जीवन श्रेणी अवतार एवं अगले जन्मदिन की उल्टी गिनती।',
    adsTitle: 'प्रायोजित विज्ञापन प्लेसमेंट',
    adsSub: 'वैश्विक पहुँच उपकरण को लगातार मुफ्त रखने में सक्षम बनाता है',
    adsPlaceholder: 'गूगल एडसेंस सैंडबॉक्स ब्लॉक - ID: ca-pub-99824681',
    genderMale: 'लड़का अवतार',
    genderFemale: 'लड़की अवतार',
    genderNeutral: 'तटस्थ अवतार',
    genderSelect: 'अवतार परिप्रेक्ष्य चुनें',
    dobPlaceholder: 'अपनी जन्म तिथि चुनें',
    analyticsTitle: 'लाइव कैलकुलेटर गतिविधि स्थिति',
    analyticsSubtitle: 'पिछले २४ घंटों में वैश्विक उपयोगिता रुझान',
    analyticsActiveUsers: 'इस समय सक्रिय उपयोगकर्ता',
    analyticsTotalCalc: 'वैश्विक उपयोगिता सूचकांक',
    analyticsVoiceSuccessRate: 'आवाज पहचान सफलता दर'
  },
  ja: {
    title: '精密年齢計算ツール',
    subtitle: '秒単位の正確な時間測定とライフカテゴリーアバターの表示',
    birthDateLabel: '生年月日',
    birthTimeLabel: '出生時刻 (任意)',
    calculateBtn: '正確な年齢を算出する',
    voiceBtnLabel: '音声入力で日付を指定',
    voiceListening: '音声を認識中... 例: 「1995年10月21日」',
    voiceProcessing: '音声から日付を抽出しています...',
    voiceError: '日付が聞き取れませんでした。「〇年〇月〇日」と言ってください。',
    voiceSuccess: '音声入力から日付を正常に取得しました！',
    voiceStopBtn: '音声入力を停止',
    themeToggle: 'テーマの切り替え',
    languageSelect: '言語を選択',
    years: '歳',
    months: 'ヶ月',
    days: '日',
    hours: '時間',
    minutes: '分',
    seconds: '秒',
    weeks: '週間',
    nextBirthday: '次の誕生日',
    birthdayCountdown: '特別な日までの秒読みカウントダウン！',
    nextBirthdayDay: '曜日',
    ageCategory: 'ライフカテゴリー',
    child: '乳幼児',
    boy: '児童',
    teenage: '青少年/ティーン',
    adult: '大人',
    senior: 'シニア世代',
    statsTitle: '詳細な時間統計分析',
    faqTitle: 'よくあるご質問（FAQ）',
    seoDescription: '秒単位で正確な年齢を測定。あなたの年代に合わせたアバターの表示、次の誕生日へのカウントダウン。',
    adsTitle: '広告掲載枠',
    adsSub: '無料のアクセシビリティーツールの維持に貢献しています',
    adsPlaceholder: 'Google AdSense サンドボックス - ID: ca-pub-99824681',
    genderMale: '男の子アバター',
    genderFemale: '女の子アバター',
    genderNeutral: '中性アバター',
    genderSelect: 'アバター表示スタイルの設定',
    dobPlaceholder: '生年月日を入力してください',
    analyticsTitle: 'ライブ計算コア・アクティビティ',
    analyticsSubtitle: '過去24時間のエンゲージメント推移',
    analyticsActiveUsers: '現在計算中のアクティブセッション',
    analyticsTotalCalc: 'グローバルアクティビティ指数',
    analyticsVoiceSuccessRate: '音声認証解析精度'
  },
  bn: {
    title: 'সঠিক বয়স ক্যালকুলেটর',
    subtitle: 'রিয়েল-টাইম সেকেন্ডের বিশ্লেষণ ও আকর্ষণীয় ক্যাটাগরি অবতার',
    birthDateLabel: 'জন্ম তারিখ',
    birthTimeLabel: 'জন্মের সময় (ঐচ্ছিক)',
    calculateBtn: 'সঠিক বয়স হিসাব করুন',
    voiceBtnLabel: 'কন্ঠস্বরের মাধ্যমে এন্ট্রি',
    voiceListening: 'আপনার কন্ঠ শুনছে... (যেমন: "অক্টোবর ২১, ১৯৯৫")',
    voiceProcessing: 'জন্মতারিখের তথ্য বিশ্লেষণ করা হচ্ছে...',
    voiceError: 'কন্ঠস্বর সনাক্ত করা যায়নি। অনুগ্রহ করে "মাস দিন বছর" পরিষ্কার বলুন।',
    voiceSuccess: 'ভয়েস কমান্ডের মাধ্যমে সফলভাবে তারিখ নেওয়া হয়েছে!',
    voiceStopBtn: 'শোনা বন্ধ করুন',
    themeToggle: 'রঙের মোড পরিবর্তন',
    languageSelect: 'ভাষা পরিবর্তন',
    years: 'বছর',
    months: 'মাস',
    days: 'দিন',
    hours: 'ঘণ্টা',
    minutes: 'মিনিট',
    seconds: 'সেকেন্ড',
    weeks: 'সপ্তাহ',
    nextBirthday: 'পরবর্তী জন্মদিন',
    birthdayCountdown: 'আপনার আসন্ন জন্মদিনের জন্য অপেক্ষার দিন!',
    nextBirthdayDay: 'জন্মদিনটি হবে',
    ageCategory: 'জীবন পর্যায়',
    child: 'শিশু',
    boy: 'কিশোর-কিশোরী',
    teenage: 'তরুণ-তরুণী',
    adult: 'প্রাপ্তবয়স্ক',
    senior: 'প্রবীণ নাগরিক',
    statsTitle: 'বিস্তারিত ঐতিহাসিক ও দিনভিত্তিক তথ্য',
    faqTitle: 'সচরাচর জিজ্ঞাসিত প্রশ্নাবলী (FAQ)',
    seoDescription: 'সেকেন্ডের সূক্ষ্মতায় আপনার সঠিক বয়স গণনা করুন। জীবন ক্যাটাগরি ফ্রেমে কাস্টম অবতার এবং স্বয়ংক্রিয় কাউন্টডাউন।',
    adsTitle: 'স্পন্সরড বিজ্ঞাপন ফ্রেম',
    adsSub: 'বিশ্বব্যাপী আমাদের এই সেবাটি সবার জন্য বিনামূল্যে রাখতে সাহায্য করে',
    adsPlaceholder: 'গুগল এডসেন্স ফিল্টার ফ্রেম - ID: ca-pub-99824681',
    genderMale: 'ছেলে অবতার',
    genderFemale: 'মেয়ে অবতার',
    genderNeutral: 'সাধারণ অবতার',
    genderSelect: 'অবতার ধরণ সিলেক্ট করুন',
    dobPlaceholder: 'আপনার জন্ম তারিখ নির্বাচন করুন',
    analyticsTitle: 'লাইভ বয়স ক্যালকুলেটর অ্যাক্টিভিটি',
    analyticsSubtitle: 'গত ২৪ ঘণ্টায় সামগ্রিক ব্যবহারের পরিসংখ্যান',
    analyticsActiveUsers: 'বর্তমানে লাইভ সেশন ব্যবহারকারী',
    analyticsTotalCalc: 'গ্লোবাল ক্যালকুলেশন সূচক',
    analyticsVoiceSuccessRate: 'ভয়েস সনাক্তকরণ সাফল্যের হার'
  },
  ar: {
    title: 'حاسبة العمر الدقيقة',
    subtitle: 'حساب دقيق للعمر بالسنوات والأشهر والأيام والثواني بلمح البصر',
    birthDateLabel: 'تاريخ الميلاد',
    birthTimeLabel: 'وقت الميلاد (اختياري)',
    calculateBtn: 'احسب العمر الدقيق',
    voiceBtnLabel: 'إدخال بالصوت',
    voiceListening: 'جاري الاستماع... (مثال: "واحد وعشرين أكتوبر ألف وتسعمائة وخمسة وتسعين")',
    voiceProcessing: 'جاري تحليل النص الصوتي...',
    voiceError: 'لم يتم فهم التاريخ بوضوح. حاول التقول بـ "اليوم الشهر السنة".',
    voiceSuccess: 'تم تحميل تاريخ الميلاد بنجاح عبر الصوت!',
    voiceStopBtn: 'إيقاف الاستماع',
    themeToggle: 'تغيير المظهر',
    languageSelect: 'اختر اللغة',
    years: 'سنوات',
    months: 'أشهر',
    days: 'أيام',
    hours: 'ساعات',
    minutes: 'دقائق',
    seconds: 'ثواني',
    weeks: 'أسابيع',
    nextBirthday: 'عيد الميلاد القادم',
    birthdayCountdown: 'الأيام المتبقية ليومك المميز الجديد!',
    nextBirthdayDay: 'يصادف يوم',
    ageCategory: 'فئة العمر الحالية',
    child: 'طفل رضيع',
    boy: 'يافع/شبل',
    teenage: 'مراهق',
    adult: 'بالغ',
    senior: 'كبار السن الكرام',
    statsTitle: 'الإحصائيات والتحليلات الزمنية الشاملة',
    faqTitle: 'الأسئلة الشائعة للباحثين عن المعرفة',
    seoDescription: 'احسب عمرك الدقيق بالثواني. احصل على رمز الفئة العمرية المخصصة وعداً تنازلياً مميزاً إلى عيد ميلادك.',
    adsTitle: 'موقع إعلان ممول مخصص',
    adsSub: 'يدعم استمرار هذه الأداة المجانية للأشخاص حول العالم',
    adsPlaceholder: 'مربع حماية غوغل أدسنس - ID: ca-pub-99824681',
    genderMale: 'أفاتار ولد',
    genderFemale: 'أفاتار فتاة',
    genderNeutral: 'أفاتار محايد',
    genderSelect: 'اختر نمط الأفاتار المفضل',
    dobPlaceholder: 'اختر تاريخ ميلادك من التقويم',
    analyticsTitle: 'مؤشرات التفاعل الحاسوبية المباشرة',
    analyticsSubtitle: 'إحصائيات الاستخدام العالمي في الـ ٢٤ ساعة الماضية',
    analyticsActiveUsers: 'المستخدمون النشطون الآن',
    analyticsTotalCalc: 'مؤشر العمليات العالمي الموحد',
    analyticsVoiceSuccessRate: 'مستوى نجاح معالج الصوت'
  }
};

export const faqs: Record<LanguageCode, FAQItem[]> = {
  en: [
    {
      id: 'faq1',
      question: 'How is the precise age calculated on this platform?',
      answer: 'We compute age using real leap year cycles, counting exact months and variable calendar days (e.g. 28, 30, or 31 days) from your birth date up to the current system millisecond in your active timezone.'
    },
    {
      id: 'faq2',
      question: 'How does the voice date-of-birth command entry work?',
      answer: 'By enabling your microphone, we trigger the browser’s localized Web Speech Recognition API. Once spoken, our premium parser scans for named months, digit numbers, and year references across English, Spanish, Hindi, Bengali, Arabic, and more, instantly inputting the correct Gregorian calendar schema.'
    },
    {
      id: 'faq3',
      question: 'How are the Life Category Avatars assigned?',
      answer: 'We classify the results as: "Child" for ages under 5, "Youth" for ages 5 to 12, "Teenager" for ages 13 to 19, "Adult" for 20 to 59, and "Golden Citizen" for 60+. Avatars instantly adapt using fluid SVGs that capture responsive attributes based on selected styles.'
    },
    {
      id: 'faq4',
      question: 'Is my input date stored on any remote cloud database?',
      answer: 'No. All calculations, speech transcript parsing, and time measurements occur strictly client-side inside your browser sandbox to ensure 100% data confidentiality and private security.'
    }
  ],
  es: [
    {
      id: 'faq1',
      question: '¿Cómo se calcula la edad precisa en esta plataforma?',
      answer: 'Se calcula calculando la diferencia exacta entre su hora de nacimiento y el momento actual, considerando bisiestos y variables de días mensuales (28, 30 o 31 días) en su zona horaria activa.'
    },
    {
      id: 'faq2',
      question: '¿Cómo funciona la entrada de fecha de nacimiento por voz?',
      answer: 'Al activar el micrófono, la API de reconocimiento de voz del navegador convierte su lenguaje hablado en texto. Nuestro parser busca nombres de meses, valores de dígitos y años para rellenar la fecha automáticamente.'
    },
    {
      id: 'faq3',
      question: '¿Cómo se asignan los avatares de categoría de vida?',
      answer: 'Se definen bajo rangos: "Niño" (menores de 5), "Joven" (5-12), "Adolescente" (13-19), "Adulto" (20-59) y "Ciudadano Dorado" (60+), con un estilo vectorial vibrante y adaptativo.'
    },
    {
      id: 'faq4',
      question: '¿Se guarda mi fecha en alguna base de datos en la nube?',
      answer: 'No. Todos los procesamientos de cálculo y voz ocurren localmente en su propio navegador en un entorno seguro y de máxima privacidad.'
    }
  ],
  fr: [
    {
      id: 'faq1',
      question: 'Comment l\'âge précis est-il calculé sur ce site ?',
      answer: 'Nous calculons la différence chronologique exacte en tenant compte des années bissextiles, des longueurs variables des mois (28, 30 ou 31 jours) et du fuseau horaire actif pour un résultat scientifique parfait.'
    },
    {
      id: 'faq2',
      question: 'Comment marche l\'accessibilité d\'entrée vocale de naissance ?',
      answer: 'Nous utilisons l\'API Web Speech pour capter votre voix. Notre algorithme extrait dynamiquement le mois, le jour et l\'année de naissance pour remplir automatiquement le calendrier.'
    },
    {
      id: 'faq3',
      question: 'Comment les catégories d\'avatars réagissent-elles ?',
      answer: 'Les tranches d\'âges sont classées ainsi : Enfant (0-4), Jeune (5-12), Adolescent (13-19), Adulte (20-59) et Citoyen d\'Or (60+). Un design SVG s\'affiche selon la perspective choisie.'
    },
    {
      id: 'faq4',
      question: 'Mes informations privées sont-elles conservées sur un serveur ?',
      answer: 'Non, aucune donnée n\'est envoyée à l\'extérieur. Le fonctionnement se fait exclusivement en local au sein de l\'application à page unique.'
    }
  ],
  de: [
    {
      id: 'faq1',
      question: 'Wie wird das genaue Alter auf dieser Seite berechnet?',
      answer: 'Wir ermitteln das Alter unter Berücksichtigung von Schaltjahren, der exakten Anzahl an Monatstagen (28, 30 oder 31) und der aktuellen Echtzeit Ihres Browsers.'
    },
    {
      id: 'faq2',
      question: 'Wie funktioniert die barrierefreie Spracheingabe?',
      answer: 'Nach Aktivierung des Mikrofons wird der gesprochene Satz interpretiert. Der Algorithmus sucht nach Monatsnamen und Ziffern und überträgt das Geburtsdatum sofort ins Datumsfeld.'
    },
    {
      id: 'faq3',
      question: 'Wie sind die Lebenskategorien für Avatare aufgeteilt?',
      answer: 'Es gibt folgende Stufen: Kind (unter 5 Jahre), Jugendliche (5-12), Teenager (13-19), Erwachsener (20-59) und Seniorenklasse (60+).'
    },
    {
      id: 'faq4',
      question: 'Werden meine eingegebenen Daten auf Servern gespeichert?',
      answer: 'Nein. Alle Berechnungen und Spracherkennungsdaten finden vollständig lokal auf Ihrem Gerät statt. Absolute Privatsphäre ist garantiert.'
    }
  ],
  hi: [
    {
      id: 'faq1',
      question: 'इस प्लेटफ़ॉर्म पर सटीक उम्र कैसे गिनी जाती है?',
      answer: 'हम आपके जन्म के समय से लेकर वर्तमान क्षण तक लीप ईयर चक्र, महीनों के सटीक दिनों (२८, ३०, या ३१ दिन) और आपके टाइमज़ोन का मिलान कर सटीक उम्र की गणना करते हैं।'
    },
    {
      id: 'faq2',
      question: 'आवाज आधारित जन्म तिथि दर्ज करने की सुविधा कैसे काम करती है?',
      answer: 'आपके माइक्रोफ़ोन की अनुमति से हम ब्राउज़र की वेब स्पीच एपीआई का उपयोग करते हैं। आपके बोलने के बाद, हमारा सिस्टम महीनों के नाम और साल के अंकों को पहचानकर तिथि को स्वचालित सेट करता है।'
    },
    {
      id: 'faq3',
      question: 'लाइफ कैटेगरी अवतार का निर्धारण कैसे होता है?',
      answer: 'आयु वर्ग इस प्रकार है: ५ वर्ष से कम पर "शिशु", ५-१२ पर "बालक/बालिका", १३-१९ पर "किशोर", २०-५९ पर "वयस्क", और ६०+ होने पर "वरिष्ठ नागरिक" का वेक्टर अवतार दिखाई देता है।'
    },
    {
      id: 'faq4',
      question: 'क्या मेरी जन्मतिथि कहीं क्लाउड में सहेज कर रखी जाती है?',
      answer: 'बिल्कुल नहीं! सुरक्षा और गोपनीयता को १००% अक्षुण्ण रखने के लिए यह कैलकुलेटर पूर्णतः आपके ब्राउज़र के अंदर कार्य करता है।'
    }
  ],
  ja: [
    {
      id: 'faq1',
      question: '年齢判定はどのようなアルゴリズムで行われていますか？',
      answer: 'うるう年、各月の正確な日数（28日、30日、31日）、お使いのブラウザのアクティブタイムゾーンでの一ミリ秒単位の時間差を割り当てて高精度に実年齢を取得します。'
    },
    {
      id: 'faq2',
      question: '生年月日の音声入力機能はどのように制御していますか？',
      answer: 'マイクが有効化されるとブラウザのWeb Speech APを実行し、日本語や多言語で話された月日・数値を年齢算出用パターンにパースして即座にカレンダーにマッピングします。'
    },
    {
      id: 'faq3',
      question: '年代ごとのキャラクターアバターの基準を教えてください。',
      answer: '0〜4歳（乳幼児）、5〜12歳（児童）、13〜19歳（ティーン）、20〜59歳（大人）、60歳以上（シニア世代）に区分され、美しく滑らかに動くアバターアートワークに投影されます。'
    },
    {
      id: 'faq4',
      question: '私の誕生日情報がサーバー等に収集されるリスクはありますか？',
      answer: 'ありません。すべての計算や音声翻訳などのパース処理はクライアント（お使いのデバイス上）で完結しているため安心してご利用いただけます。'
    }
  ],
  bn: [
    {
      id: 'faq1',
      question: 'এই প্ল্যাটফর্মে কীভাবে একদম নিখুঁত বয়স হিসাব করা হচ্ছে?',
      answer: 'অধিবর্ষ (লিপ ইয়ার), মাসের নির্দিষ্ট দিনসংখ্যা (২৮, ৩০ বা ৩১ দিন) এবং জন্ম তারিখ হতে চলতি সময়ের সঠিক মিলি সেকেন্ড পর্যন্ত আপনার সক্রিয় টাইমজোন মিলিয়ে বয়স হিসাব করা হয়।'
    },
    {
      id: 'faq2',
      question: 'ভয়েস কমান্ডের মাধ্যমে জন্মদিন ইনপুট করার প্রক্রিয়াটি কী?',
      answer: 'আপনার মাইক্রোফোন সক্রিয় করার পর, আমরা ব্রাউজারের ওয়েব স্পিচ রিকগনিশন এপিআই ট্রিগার করি। আপনি যখন তারিখ বলেন, আমাদের অ্যালগরিদম বাংলা বা ইংরেজিতে বলা মাসের নাম ও বছর স্বয়ংক্রিয়ভাবে ইনপুট বক্সে লিখে দেয়।'
    },
    {
      id: 'faq3',
      question: 'কোন বয়সসীমায় কী ধরণের লাইফ ক্যাটাগরি অবতার দেখানো হয়?',
      answer: 'বয়সের ভিত্তিতে ৫ বছরের নিচে "শিশু", ৫-১২ বছর "কিশোর-কিশোরী", ১৩-১৯ বছর "তরুণ-তরুণী", ২০-৫৯ বছর "প্রাপ্তবয়স্ক" এবং ৬০ বছরের বেশি বয়সীদের সুন্দর "প্রবীণ নাগরিক" চমৎকার ভেক্টর চরিত্রে পরিবর্তন করা হয়।'
    },
    {
      id: 'faq4',
      question: 'আমার দেওয়া ব্যক্তিগত জন্ম তারিখ কি কোনো সার্ভারে জমা থাকে?',
      answer: 'না, কোনো সার্ভারে আপনার তথ্য পাঠানো হয় না। সকল হিসাব এবং ভয়েস সনাক্তকরণ শতভাগ সুরক্ষিতভাবে আপনার ব্রাউজারেই সম্পন্ন হয়।'
    }
  ],
  ar: [
    {
      id: 'faq1',
      question: 'كيف تحسب الآلة عمر دقيق للمستعلم؟',
      answer: 'نقوم بالعد المتطابق بالثواني بالرجوع لدورات الأعوام الكبيسة وعدد أيام الأشهر المتقبلة (٢٨ أو ٣٠ أو ٣١ يوماً) لكي يعطي النتيجة بدقة حيوية متطابقة تماماً.'
    },
    {
      id: 'faq2',
      question: 'كيف يتغلغل نظام الاستماع الصوتي لدخول العمر بالمنطوق؟',
      answer: 'عبر تليين الميكروفون الموجه، تباشر واجهة المستشعر تحليل المسموع كأقسام للزمن والتقويم الهجري الشمسي تلقائياً لتركيب دالة تاريخ حية دون لمس الأزرار.'
    },
    {
      id: 'faq3',
      question: 'ما هي معايير تصنيف شخصيات الأفاتار العمرية الملخصة؟',
      answer: 'العتبات مدروسة كالتالي: طفل (تحت ٥ سنوات)، يافع (٥-١٢ سنة)، مراهق (١٣-١٩ سنة)، بالغ (٢٠-٥٩ سنة)، كبار السن الموقرين (٦٠ سنة فما فوق).'
    },
    {
      id: 'faq4',
      question: 'هل يخزن خادم عن بعد معطيات مولدي وسري الديموغرافي؟',
      answer: 'لا على الإطلاق. تعمل الحاسبة حصرياً وبشكل آمن داخل بيئة متصفحك للحفاظ على خصوصيتك وسريتك بنسبة ١٠٠ بالمائة.'
    }
  ]
};
