import { TranslationDict, FAQItem, LanguageCode } from './types';

export const translations: Record<LanguageCode, TranslationDict> = {
  en: {
    title: 'Age Calculator',
    subtitle: 'High precision age, exact breakdown & premium statistics',
    birthDateLabel: 'Date of Birth',
    birthTimeLabel: 'Time of Birth (Optional)',
    calculateBtn: 'Calculate Age',
    voiceBtnLabel: 'Voice Input DOB',
    voiceListening: 'Listening for Date of Birth... (e.g. "October twenty-first nineteen ninety-five")',
    voiceProcessing: 'Parsing spoke date text...',
    voiceError: 'Could not catch date clearly. Try saying "Month Day Year".',
    voiceSuccess: 'Successfully loaded date from voice command!',
    voiceStopBtn: 'Stop Listening',
    themeToggle: 'Toggle Theme',
    languageSelect: 'Choose Language',
    years: 'Years',
    months: 'Months',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    weeks: 'Weeks',
    nextBirthday: 'Next Birthday',
    birthdayCountdown: 'Days left until your special day!',
    nextBirthdayDay: 'Falls on',
    ageCategory: 'Life Category',
    child: 'Child',
    boy: 'Youth',
    teenage: 'Teenager',
    adult: 'Adult',
    senior: 'Golden Citizen',
    statsTitle: 'Chronological Insights & Statistics',
    faqTitle: 'Frequently Asked Questions (FAQ)',
    seoDescription: 'Calculate your precise age down to the second. Find your life category avatar and countdown to the next birthday.',
    adsTitle: 'Sponsored Ad Placement',
    adsSub: 'Supports free global accessibility tools',
    adsPlaceholder: 'Google AdSense Sandbox Block - Code ID: ca-pub-99824681',
    genderMale: 'Boy Avatar',
    genderFemale: 'Girl Avatar',
    genderNeutral: 'Neutral Avatar',
    genderSelect: 'Choose Avatar Perspective',
    dobPlaceholder: 'Select your birth date',
    analyticsTitle: 'Live Calculator Engagement Platform',
    analyticsSubtitle: 'Global usage trends over the last 24 hours',
    analyticsActiveUsers: 'Active Calculators Right Now',
    analyticsTotalCalc: 'Global App Usage Index',
    analyticsVoiceSuccessRate: 'Voice Parser Accuracy Rate'
  },
  es: {
    title: 'Calculadora de Edad',
    subtitle: 'Cálculo de edad de alta precisión con desglose exacto',
    birthDateLabel: 'Fecha de Nacimiento',
    birthTimeLabel: 'Hora de Nacimiento (Opcional)',
    calculateBtn: 'Calcular Edad',
    voiceBtnLabel: 'Entrada por Voz',
    voiceListening: 'Escuchando fecha... (ej: "Veintiuno de octubre de mil novecientos noventa y cinco")',
    voiceProcessing: 'Procesando texto de voz...',
    voiceError: 'No se pudo entender la fecha. Intente decir "Día Mes Año".',
    voiceSuccess: '¡Fecha cargada con éxito por voz!',
    voiceStopBtn: 'Detener de escuchar',
    themeToggle: 'Cambiar Tema',
    languageSelect: 'Elegir Idioma',
    years: 'Años',
    months: 'Meses',
    days: 'Días',
    hours: 'Horas',
    minutes: 'Minutos',
    seconds: 'Segundos',
    weeks: 'Semanas',
    nextBirthday: 'Siguiente Cumpleaños',
    birthdayCountdown: '¡Días que faltan para tu gran día!',
    nextBirthdayDay: 'Cae en',
    ageCategory: 'Categoría de Vida',
    child: 'Niño',
    boy: 'Joven',
    teenage: 'Adolescente',
    adult: 'Adulto',
    senior: 'Ciudadano Dorado',
    statsTitle: 'Estadísticas Cronológicas Detalladas',
    faqTitle: 'Preguntas Frecuentes (FAQ)',
    seoDescription: 'Calcula tu edad precisa hasta el segundo. Encuentra tu avatar de categoría de vida y la cuenta regresiva.',
    adsTitle: 'Colocación de Anuncio Patrocinado',
    adsSub: 'Soporta herramientas gratuitas accesibles en el mundo',
    adsPlaceholder: 'Bloque AdSense Sandbox - ID: ca-pub-99824681',
    genderMale: 'Avatar Chico',
    genderFemale: 'Avatar Chica',
    genderNeutral: 'Avatar Neutro',
    genderSelect: 'Elige Perspectiva de Avatar',
    dobPlaceholder: 'Selecciona tu fecha de nacimiento',
    analyticsTitle: 'Plataforma de Participación en Vivo',
    analyticsSubtitle: 'Tendencias de uso global en las últimas 24 horas',
    analyticsActiveUsers: 'Calculadoras Activas Ahora',
    analyticsTotalCalc: 'Índice de Uso Global',
    analyticsVoiceSuccessRate: 'Tasa de Éxito de Voz'
  },
  fr: {
    title: 'Calculateur d\'Âge Précis',
    subtitle: 'Âge exact en temps réel avec statistiques premium',
    birthDateLabel: 'Date de Naissance',
    birthTimeLabel: 'Heure de Naissance (Optionnel)',
    calculateBtn: 'Calculer l\'Âge Exact',
    voiceBtnLabel: 'Entrée Vocale',
    voiceListening: 'À l\'écoute... (ex: "Le premier janvier mille neuf cent quatre-vingt-dix")',
    voiceProcessing: 'Analyse de la voix...',
    voiceError: 'Date non reconnue, réessayez : "Jour Mois Année".',
    voiceSuccess: 'Date chargée par commande vocale !',
    voiceStopBtn: 'Arrêter l\'écoute',
    themeToggle: 'Changer de Thème',
    languageSelect: 'Choisir la Langue',
    years: 'Ans',
    months: 'Mois',
    days: 'Jours',
    hours: 'Heures',
    minutes: 'Minutes',
    seconds: 'Secondes',
    weeks: 'Semaines',
    nextBirthday: 'Prochain Anniversaire',
    birthdayCountdown: 'Jours restants avant votre journée spéciale !',
    nextBirthdayDay: 'Tombe un',
    ageCategory: 'Catégorie de Vie',
    child: 'Enfant',
    boy: 'Jeune',
    teenage: 'Adolescent',
    adult: 'Adulte',
    senior: 'Citoyen d\'Or',
    statsTitle: 'Statistiques Chronologiques Visuelles',
    faqTitle: 'Foire Aux Questions (FAQ)',
    seoDescription: 'Calculez votre âge précis à la seconde près. Découvrez votre avatar et le compte à rebours d\'anniversaire.',
    adsTitle: 'Emplacement Publicitaire Sponsorisé',
    adsSub: 'Prend en charge les outils d\'accessibilité mondiaux gratuits',
    adsPlaceholder: 'Sandbox Google AdSense - ID: ca-pub-99824681',
    genderMale: 'Avatar Garçon',
    genderFemale: 'Avatar Fille',
    genderNeutral: 'Avatar Neutre',
    genderSelect: 'Choisir la Perspective de l\'Avatar',
    dobPlaceholder: 'Sélectionnez votre date',
    analyticsTitle: 'Engagement de la Calculatrice en Direct',
    analyticsSubtitle: 'Tendances d\'utilisation globale ces dernières 24h',
    analyticsActiveUsers: 'Utilisateurs Actifs en Direct',
    analyticsTotalCalc: 'Index d\'Utilisation Globale',
    analyticsVoiceSuccessRate: 'Taux de Réussite Vocale'
  },
  de: {
    title: 'Präziser Altersrechner',
    subtitle: 'Hochpräzise Altersanalysen & Premium-Lebensstatistiken',
    birthDateLabel: 'Geburtsdatum',
    birthTimeLabel: 'Geburtszeit (Optional)',
    calculateBtn: 'Präzises Alter berechnen',
    voiceBtnLabel: 'Spracheingabe Geburtsdatum',
    voiceListening: 'Zuhören... (z.B. "Erster Januar neunzehnhundertneunzig")',
    voiceProcessing: 'Parsed Spracheingabe...',
    voiceError: 'Datum wurde nicht verstanden. Bitte "Tag Monat Jahr" aussprechen.',
    voiceSuccess: 'Geburtsdatum per Sprachbefehl geladen!',
    voiceStopBtn: 'Zuhören stoppen',
    themeToggle: 'Thema wechseln',
    languageSelect: 'Sprache wählen',
    years: 'Jahre',
    months: 'Monate',
    days: 'Tage',
    hours: 'Stunden',
    minutes: 'Minuten',
    seconds: 'Sekunden',
    weeks: 'Wochen',
    nextBirthday: 'Nächster Geburtstag',
    birthdayCountdown: 'Tage verbleibend bis zu Ihrem Ehrentag!',
    nextBirthdayDay: 'Fällt auf einen',
    ageCategory: 'Lebenskategorie',
    child: 'Kind',
    boy: 'Junge/Mädchen',
    teenage: 'Jugendliche(r)',
    adult: 'Erwachsene(r)',
    senior: 'Seniorenklasse',
    statsTitle: 'Chronologische Einblicke & Statistiken',
    faqTitle: 'Häufig gestellte Fragen (FAQ)',
    seoDescription: 'Berechnen Sie Ihr präzises Alter sekundengenau. Finden Sie Ihr Lebensavatar und Ihren Countdown.',
    adsTitle: 'Gesponserte Platzierung',
    adsSub: 'Unterstützt die Bereitstellung barrierefreier Tools weltweit',
    adsPlaceholder: 'Google AdSense-Sandbox - ID: ca-pub-99824681',
    genderMale: 'Männliches Avatar',
    genderFemale: 'Weibliches Avatar',
    genderNeutral: 'Neutrales Avatar',
    genderSelect: 'Avatar-Stil auswählen',
    dobPlaceholder: 'Geburtsdatum auswählen',
    analyticsTitle: 'Echtzeit-Plattform-Engagement',
    analyticsSubtitle: 'Globale Nutzungstrends der letzten 24 Stunden',
    analyticsActiveUsers: 'Aktive Nutzer im Rechner',
    analyticsTotalCalc: 'Globaler Nutzungsindex',
    analyticsVoiceSuccessRate: 'Spracherkennung Genauigkeitsrate'
  },
  hi: {
    title: 'सटीक उम्र कैलकुलेटर',
    subtitle: 'उच्च सटीकता के साथ अपनी उम्र, महीने, और दिन की सटीक गणना करें',
    birthDateLabel: 'जन्म तिथि',
    birthTimeLabel: 'जन्म का समय (वैकल्पिक)',
    calculateBtn: 'सटीक आयु की गणना करें',
    voiceBtnLabel: 'आवाज से तिथि दर्ज करें',
    voiceListening: 'जन्मतिथि की आवाज सुन रहे हैं... (जैसे: "पंद्रह अगस्त उन्नीस सौ90")',
    voiceProcessing: 'आवाज का विश्लेषण कर रहे हैं...',
    voiceError: 'तिथि स्पष्ट नहीं मिली। "महीना दिन साल" बोलकर देखें।',
    voiceSuccess: 'आवाज संकेत से जन्म तिथि सफलतापूर्वक दर्ज की गई!',
    voiceStopBtn: 'सुनना बंद करें',
    themeToggle: 'थीम बदलें',
    languageSelect: 'भाषा का चयन करें',
    years: 'वर्ष',
    months: 'महीने',
    days: 'दिन',
    hours: 'घंटे',
    minutes: 'मिनट',
    seconds: 'सेकंड',
    weeks: 'सप्ताह',
    nextBirthday: 'अगला जन्मदिन',
    birthdayCountdown: 'आपके विशेष दिन के लिए बचे हुए दिन!',
    nextBirthdayDay: 'दिन पड़ता है',
    ageCategory: 'जीवन श्रेणी',
    child: 'शिशु',
    boy: 'बालक/बालिका',
    teenage: 'किशोर',
    adult: 'वयस्क',
    senior: 'वरिष्ठ नागरिक',
    statsTitle: 'कालानुक्रमिक अंतर्दृष्टि और रुझान',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न (FAQ)',
    seoDescription: 'पैक की गई सेकंड सटीकता के साथ अपनी सटीक आयु की गणना करें। जीवन श्रेणी अवतार एवं अगले जन्मदिन की उल्टी गिनती।',
    adsTitle: 'प्रायोजित विज्ञापन प्लेसमेंट',
    adsSub: 'वैश्विक पहुँच उपकरण को लगातार मुफ्त रखने में सक्षम बनाता है',
    adsPlaceholder: 'गूगल एडसेंस सैंडबॉक्स ब्लॉक - ID: ca-pub-99824681',
    genderMale: 'लड़का अवतार',
    genderFemale: 'लड़की अवतार',
    genderNeutral: 'तटस्थ अवतार',
    genderSelect: 'अवतार परिप्रेक्ष्य चुनें',
    dobPlaceholder: 'अपनी जन्म तिथि चुनें',
    analyticsTitle: 'लाइव कैलकुलेटर गतिविधि स्थिति',
    analyticsSubtitle: 'पिछले २४ घंटों में वैश्विक उपयोगिता रुझान',
    analyticsActiveUsers: 'इस समय सक्रिय उपयोगकर्ता',
    analyticsTotalCalc: 'वैश्विक उपयोगिता सूचकांक',
    analyticsVoiceSuccessRate: 'आवाज पहचान सफलता दर'
  },
  ja: {
    title: '精密年齢計算ツール',
    subtitle: '秒単位の正確な時間測定とライフカテゴリーアバターの表示',
    birthDateLabel: '生年月日',
    birthTimeLabel: '出生時刻 (任意)',
    calculateBtn: '正確な年齢を算出する',
    voiceBtnLabel: '音声入力で日付を指定',
    voiceListening: '音声を認識中... 例: 「1995年10月21日」',
    voiceProcessing: '音声から日付を抽出しています...',
    voiceError: '日付が聞き取れませんでした。「〇年〇月〇日」と言ってください。',
    voiceSuccess: '音声入力から日付を正常に取得しました！',
    voiceStopBtn: '音声入力を停止',
    themeToggle: 'テーマの切り替え',
    languageSelect: '言語を選択',
    years: '歳',
    months: 'ヶ月',
    days: '日',
    hours: '時間',
    minutes: '分',
    seconds: '秒',
    weeks: '週間',
    nextBirthday: '次の誕生日',
    birthdayCountdown: '特別な日までの秒読みカウントダウン！',
    nextBirthdayDay: '曜日',
    ageCategory: 'ライフカテゴリー',
    child: '乳幼児',
    boy: '児童',
    teenage: '青少年/ティーン',
    adult: '大人',
    senior: 'シニア世代',
    statsTitle: '詳細な時間統計分析',
    faqTitle: 'よくあるご質問（FAQ）',
    seoDescription: '秒単位で正確な年齢を測定。あなたの年代に合わせたアバターの表示、次の誕生日へのカウントダウン。',
    adsTitle: '広告掲載枠',
    adsSub: '無料のアクセシビリティーツールの維持に貢献しています',
    adsPlaceholder: 'Google AdSense サンドボックス - ID: ca-pub-99824681',
    genderMale: '男の子アバター',
    genderFemale: '女の子アバター',
    genderNeutral: '中性アバター',
    genderSelect: 'アバター表示スタイルの設定',
    dobPlaceholder: '生年月日を入力してください',
    analyticsTitle: 'ライブ計算コア・アクティビティ',
    analyticsSubtitle: '過去24時間のエンゲージメント推移',
    analyticsActiveUsers: '現在計算中のアクティブセッション',
    analyticsTotalCalc: 'グローバルアクティビティ指数',
    analyticsVoiceSuccessRate: '音声認証解析精度'
  },
  bn: {
    title: 'বয়স ক্যালকুলেটর',
    subtitle: 'রিয়েল-টাইম সেকেন্ডের বিশ্লেষণ ও আকর্ষণীয় ক্যাটাগরি অবতার',
    birthDateLabel: 'জন্ম তারিখ',
    birthTimeLabel: 'জন্মের সময় (ঐচ্ছিক)',
    calculateBtn: 'বয়স হিসাব করুন',
    voiceBtnLabel: 'কন্ঠস্বরের মাধ্যমে এন্ট্রি',
    voiceListening: 'আপনার কন্ঠ শুনছে... (যেমন: "অক্টোবর ২১, ১৯৯৫")',
    voiceProcessing: 'জন্মতারিখের তথ্য বিশ্লেষণ করা হচ্ছে...',
    voiceError: 'কন্ঠস্বর সনাক্ত করা যায়নি। অনুগ্রহ করে "মাস দিন বছর" পরিষ্কার বলুন।',
    voiceSuccess: 'ভয়েস কমান্ডের মাধ্যমে সফলভাবে তারিখ নেওয়া হয়েছে!',
    voiceStopBtn: 'শোনা বন্ধ করুন',
    themeToggle: 'রঙের মোড পরিবর্তন',
    languageSelect: 'ভাষা পরিবর্তন',
    years: 'বছর',
    months: 'মাস',
    days: 'দিন',
    hours: 'ঘণ্টা',
    minutes: 'মিনিট',
    seconds: 'সেকেন্ড',
    weeks: 'সপ্তাহ',
    nextBirthday: 'পরবর্তী জন্মদিন',
    birthdayCountdown: 'আপনার আসন্ন জন্মদিনের জন্য অপেক্ষার দিন!',
    nextBirthdayDay: 'জন্মদিনটি হবে',
    ageCategory: 'জীবন পর্যায়',
    child: 'শিশু',
    boy: 'কিশোর-কিশোরী',
    teenage: 'তরুণ-তরুণী',
    adult: 'প্রাপ্তবয়স্ক',
    senior: 'প্রবীণ নাগরিক',
    statsTitle: 'বিস্তারিত ঐতিহাসিক ও দিনভিত্তিক তথ্য',
    faqTitle: 'সচরাচর জিজ্ঞাসিত প্রশ্নাবলী (FAQ)',
    seoDescription: 'সেকেন্ডের সূক্ষ্মতায় আপনার সঠিক বয়স গণনা করুন। জীবন ক্যাটাগরি ফ্রেমে কাস্টম অবতার এবং স্বয়ংক্রিয় কাউন্টডাউন।',
    adsTitle: 'স্পন্সরড বিজ্ঞাপন ফ্রেম',
    adsSub: 'বিশ্বব্যাপী আমাদের এই সেবাটি সবার জন্য বিনামূল্যে রাখতে সাহায্য করে',
    adsPlaceholder: 'গুগল এডসেন্স ফিল্টার ফ্রেম - ID: ca-pub-99824681',
    genderMale: 'ছেলে অবতার',
    genderFemale: 'মেয়ে অবতার',
    genderNeutral: 'সাধারণ অবতার',
    genderSelect: 'অবতার ধরণ সিলেক্ট করুন',
    dobPlaceholder: 'আপনার জন্ম তারিখ নির্বাচন করুন',
    analyticsTitle: 'লাইভ বয়স ক্যালকুলেটর অ্যাক্টিভিটি',
    analyticsSubtitle: 'গত ২৪ ঘণ্টায় সামগ্রিক ব্যবহারের পরিসংখ্যান',
    analyticsActiveUsers: 'বর্তমানে লাইভ সেশন ব্যবহারকারী',
    analyticsTotalCalc: 'গ্লোবাল ক্যালকুলেশন সূচক',
    analyticsVoiceSuccessRate: 'ভয়েস সনাক্তকরণ সাফল্যের হার'
  },
  ar: {
    title: 'حاسبة العمر الدقيقة',
    subtitle: 'حساب دقيق للعمر بالسنوات والأشهر والأيام والثواني بلمح البصر',
    birthDateLabel: 'تاريخ الميلاد',
    birthTimeLabel: 'وقت الميلاد (اختياري)',
    calculateBtn: 'احسب العمر الدقيق',
    voiceBtnLabel: 'إدخال بالصوت',
    voiceListening: 'جاري الاستماع... (مثال: "واحد وعشرين أكتوبر ألف وتسعمائة وخمسة وتسعين")',
    voiceProcessing: 'جاري تحليل النص الصوتي...',
    voiceError: 'لم يتم فهم التاريخ بوضوح. حاول التقول بـ "اليوم الشهر السنة".',
    voiceSuccess: 'تم تحميل تاريخ الميلاد بنجاح عبر الصوت!',
    voiceStopBtn: 'إيقاف الاستماع',
    themeToggle: 'تغيير المظهر',
    languageSelect: 'اختر اللغة',
    years: 'سنوات',
    months: 'أشهر',
    days: 'أيام',
    hours: 'ساعات',
    minutes: 'دقائق',
    seconds: 'ثواني',
    weeks: 'أسابيع',
    nextBirthday: 'عيد الميلاد القادم',
    birthdayCountdown: 'الأيام المتبقية ليومك المميز الجديد!',
    nextBirthdayDay: 'يصادف يوم',
    ageCategory: 'فئة العمر الحالية',
    child: 'طفل رضيع',
    boy: 'يافع/شبل',
    teenage: 'مراهق',
    adult: 'بالغ',
    senior: 'كبار السن الكرام',
    statsTitle: 'الإحصائيات والتحليلات الزمنية الشاملة',
    faqTitle: 'الأسئلة الشائعة للباحثين عن المعرفة',
    seoDescription: 'احسب عمرك الدقيق بالثواني. احصل على رمز الفئة العمرية المخصصة وعداً تنازلياً مميزاً إلى عيد ميلادك.',
    adsTitle: 'موقع إعلان ممول مخصص',
    adsSub: 'يدعم استمرار هذه الأداة المجانية للأشخاص حول العالم',
    adsPlaceholder: 'مربع حماية غوغل أدسنس - ID: ca-pub-99824681',
    genderMale: 'أفاتار ولد',
    genderFemale: 'أفاتار فتاة',
    genderNeutral: 'أفاتار محايد',
    genderSelect: 'اختر نمط الأفاتار المفضل',
    dobPlaceholder: 'اختر تاريخ ميلادك من التقويم',
    analyticsTitle: 'مؤشرات التفاعل الحاسوبية المباشرة',
    analyticsSubtitle: 'إحصائيات الاستخدام العالمي في الـ ٢٤ ساعة الماضية',
    analyticsActiveUsers: 'المستخدمون النشطون الآن',
    analyticsTotalCalc: 'مؤشر العمليات العالمي الموحد',
    analyticsVoiceSuccessRate: 'مستوى نجاح معالج الصوت'
  },
  pt: {
    title: 'Calculadora de Idade Precisa',
    subtitle: 'Idade de alta precisão, detalhamento exato e estatísticas premium',
    birthDateLabel: 'Data de Nascimento',
    birthTimeLabel: 'Hora de Nascimento (Opcional)',
    calculateBtn: 'Calcular Idade Precisa',
    voiceBtnLabel: 'Entrada de Voz',
    voiceListening: 'Ouvindo a data de nascimento... (ex: "vinte e um de outubro de mil novecentos e noventa e cinco")',
    voiceProcessing: 'Analisando o texto da voz...',
    voiceError: 'Não foi possível entender a data. Tente falar "Mês Dia Ano".',
    voiceSuccess: 'Data carregada com sucesso do comando de voz!',
    voiceStopBtn: 'Parar de Ouvir',
    themeToggle: 'Alternar Tema',
    languageSelect: 'Escolher Idioma',
    years: 'Anos',
    months: 'Meses',
    days: 'Dias',
    hours: 'Horas',
    minutes: 'Minutos',
    seconds: 'Segundos',
    weeks: 'Semanas',
    nextBirthday: 'Próximo Aniversário',
    birthdayCountdown: 'Dias restantes até o seu dia especial!',
    nextBirthdayDay: 'Cai em',
    ageCategory: 'Categoria de Vida',
    child: 'Criança',
    boy: 'Jovem',
    teenage: 'Adolescente',
    adult: 'Adulto',
    senior: 'Cidadão de Ouro',
    statsTitle: 'Informações e Estatísticas Cronológicas',
    faqTitle: 'Perguntas Frequentes (FAQ)',
    seoDescription: 'Calcule sua idade exata até o segundo. Descubra o seu avatar e contagem regressiva para o próximo aniversário.',
    adsTitle: 'Anúncio Patrocinado',
    adsSub: 'Apoia ferramentas de acessibilidade globais gratuitas',
    adsPlaceholder: 'Sandbox do Google AdSense - ID: ca-pub-99824681',
    genderMale: 'Avatar de Menino',
    genderFemale: 'Avatar de Menina',
    genderNeutral: 'Avatar Neutro',
    genderSelect: 'Escolha a Perspectiva do Avatar',
    dobPlaceholder: 'Selecione sua data de nascimento',
    analyticsTitle: 'Plataforma de Engajamento da Calculadora',
    analyticsSubtitle: 'Tendências globais de uso nas últimas 24 horas',
    analyticsActiveUsers: 'Calculadoras Ativas Agora',
    analyticsTotalCalc: 'Índice de Uso Global do App',
    analyticsVoiceSuccessRate: 'Taxa de Precisão do Reconhecimento de Voz'
  },
  ru: {
    title: 'Точный калькулятор возраста',
    subtitle: 'Высокоточный расчет возраста, точная разбивка и статистика',
    birthDateLabel: 'Дата рождения',
    birthTimeLabel: 'Время рождения (опционально)',
    calculateBtn: 'Рассчитать точный возраст',
    voiceBtnLabel: 'Голосовой ввод даты',
    voiceListening: 'Слушаем дату рождения... (например, "двадцать первое октября тысяча девятьсот девяносто пятого года")',
    voiceProcessing: 'Анализ голосового ввода...',
    voiceError: 'Не удалось четко распознать дату. Попробуйте сказать "Месяц День Год".',
    voiceSuccess: 'Дата успешно загружена из голосовой команды!',
    voiceStopBtn: 'Остановить прослушивание',
    themeToggle: 'Переключить тему',
    languageSelect: 'Выбрать язык',
    years: 'Лет',
    months: 'Месяцев',
    days: 'Дней',
    hours: 'Часов',
    minutes: 'Минут',
    seconds: 'Секунд',
    weeks: 'Недели',
    nextBirthday: 'Следующий день рождения',
    birthdayCountdown: 'Дней осталось до вашего праздника!',
    nextBirthdayDay: 'Выпадает на',
    ageCategory: 'Жизненный этап',
    child: 'Ребенок',
    boy: 'Молодежь',
    teenage: 'Подросток',
    adult: 'Взрослый',
    senior: 'Золотой возраст',
    statsTitle: 'Хронологическая статистика и данные',
    faqTitle: 'Часто задаваемые вопросы (FAQ)',
    seoDescription: 'Рассчитайте свой точный возраст до секунды. Узнайте свой аватар жизненного этапа и обратный отсчет.',
    adsTitle: 'Спонсорская реклама',
    adsSub: 'Поддерживает бесплатные глобальные инструменты доступности',
    adsPlaceholder: 'Песочница Google AdSense - ID: ca-pub-99824681',
    genderMale: 'Аватар мальчика',
    genderFemale: 'Аватар девочки',
    genderNeutral: 'Нейтральный аватар',
    genderSelect: 'Выберите перспективу аватара',
    dobPlaceholder: 'Выберите дату рождения',
    analyticsTitle: 'Активность пользователей калькулятора',
    analyticsSubtitle: 'Глобальные тренды за последние 24 часа',
    analyticsActiveUsers: 'Активных расчетов сейчас',
    analyticsTotalCalc: 'Глобальный индекс использования',
    analyticsVoiceSuccessRate: 'Точность распознавания голоса'
  },
  zh: {
    title: '精准年龄计算器',
    subtitle: '高精度年龄计算、精确细分与高级统计数据',
    birthDateLabel: '出生日期',
    birthTimeLabel: '出生时间 (可选)',
    calculateBtn: '计算精准年龄',
    voiceBtnLabel: '语音输入生日',
    voiceListening: '正在倾听出生日期... (例如："一九九五年十月二十一日")',
    voiceProcessing: '解析生日语音字句...',
    voiceError: '未能清晰识别日期。请尝试说出类似 "十月 二十一日 一九九五年" 或者 "1995年10月21日"。',
    voiceSuccess: '已成功从语音命令载入日期！',
    voiceStopBtn: '停止倾听',
    themeToggle: '切换主题',
    languageSelect: '选择语言',
    years: '岁',
    months: '月',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒',
    weeks: '周',
    nextBirthday: '下一个生日',
    birthdayCountdown: '距离您的特别日子还剩几天！',
    nextBirthdayDay: '生日星期',
    ageCategory: '人生成长阶段',
    child: '幼儿',
    boy: '青少年/儿童',
    teenage: '少年',
    adult: '成年人',
    senior: '金龄长者',
    statsTitle: '时间流逝分析与统计数据',
    faqTitle: '常见问题解答 (FAQ)',
    seoDescription: '精准计算您的年龄至秒级单位。显示专属于您的人生成长段位头像并进行生日追光倒计时。',
    adsTitle: '赞助商广告推荐',
    adsSub: '支持全球残障级免费包容性便利工具的持续提供',
    adsPlaceholder: 'Google AdSense 演示广告沙箱 - ID: ca-pub-99824681',
    genderMale: '男生头像',
    genderFemale: '女生头像',
    genderNeutral: '中性头像',
    genderSelect: '设置专属头像视角',
    dobPlaceholder: '点选您的出生日期',
    analyticsTitle: '在线年龄计算器活跃度看板',
    analyticsSubtitle: '过去24小时内全球交互量和使用分布趋势',
    analyticsActiveUsers: '目前全球正在计算的人数',
    analyticsTotalCalc: '全球用户总计算频次指数',
    analyticsVoiceSuccessRate: '语音转化器准确度记录率'
  },
  it: {
    title: 'Calcolatore dell\'Età Preciso',
    subtitle: 'Calcolo dell\'età ad altissima precisione, ripartizione esatta e statistiche premium',
    birthDateLabel: 'Data di Nascita',
    birthTimeLabel: 'Ora di Nascita (Opzionale)',
    calculateBtn: 'Calcola Età Esatta',
    voiceBtnLabel: 'Input Vocale',
    voiceListening: 'In ascolto per la data di nascita... (es: "ventuno ottobre millenovecentonovantacinque")',
    voiceProcessing: 'Analisi della data pronunciata...',
    voiceError: 'Non è stato possibile comprendere chiaramente la data. Prova a dire "Giorno Mese Anno".',
    voiceSuccess: 'Data caricata con successo tramite comando vocale!',
    voiceStopBtn: 'Interrompi Ascolto',
    themeToggle: 'Cambia Tema',
    languageSelect: 'Scegli Lingua',
    years: 'Anni',
    months: 'Mesi',
    days: 'Giorni',
    hours: 'Ore',
    minutes: 'Minuti',
    seconds: 'Secondi',
    weeks: 'Settimane',
    nextBirthday: 'Prossimo Compleanno',
    birthdayCountdown: 'Giorni mancanti al tuo giorno speciale!',
    nextBirthdayDay: 'Cadrà di',
    ageCategory: 'Categoria della Vita',
    child: 'Neonato',
    boy: 'Giovane',
    teenage: 'Adolescente',
    adult: 'Adulto',
    senior: 'Cittadino d\'Oro',
    statsTitle: 'Approfondimenti e Statistiche Cronologiche',
    faqTitle: 'Domande Frequenti (FAQ)',
    seoDescription: 'Calcola la tua età precisa fino al secondo. Scopri l\'avatar della tua categoria della vita e la countdown.',
    adsTitle: 'Annuncio Sponsorizzato',
    adsSub: 'Supporta strumenti gratuiti di accessibilità globale',
    adsPlaceholder: 'Sandbox Google AdSense - ID: ca-pub-99824681',
    genderMale: 'Avatar Ragazzo',
    genderFemale: 'Avatar Ragazza',
    genderNeutral: 'Avatar Neutro',
    genderSelect: 'Scegli la Prospettiva dell\'Avatar',
    dobPlaceholder: 'Seleziona la data di nascita',
    analyticsTitle: 'Piattaforma di Coinvolgimento dei Calcolatori',
    analyticsSubtitle: 'Tendenze d\'uso globale nelle ultime 24 ore',
    analyticsActiveUsers: 'Calcolatori Attivi Ora',
    analyticsTotalCalc: 'Indice di Utilizzo Globale',
    analyticsVoiceSuccessRate: 'Percentuale Successo Rilevatore Vocale'
  },
  tr: {
    title: 'Hassas Yaş Hesaplayıcı',
    subtitle: 'Yüksek çözünürlüklü yaş hesaplama, detaylı kronolojik analizler',
    birthDateLabel: 'Doğum Tarihi',
    birthTimeLabel: 'Doğum Saati (İsteğe Bağlı)',
    calculateBtn: 'Hassas Yaşı Hesapla',
    voiceBtnLabel: 'Sesli Giriş Yap',
    voiceListening: 'Doğum tarihi dinleniyor... (Örn: "yirmi bir ekim bin dokuz yüz doksan beş")',
    voiceProcessing: 'Sesli komut çözümleniyor...',
    voiceError: 'Tarih tam anlaşılamadı. Lütfen "Gün Ay Yıl" şeklinde tekrar söyleyin.',
    voiceSuccess: 'Doğham tarihi sesli komutla başarıyla yüklendi!',
    voiceStopBtn: 'Dinlemeyi Durdur',
    themeToggle: 'Temayı Değiştir',
    languageSelect: 'Dil Seçin',
    years: 'Yıl',
    months: 'Ay',
    days: 'Gün',
    hours: 'Saat',
    minutes: 'Dakika',
    seconds: 'Saniye',
    weeks: 'Hafta',
    nextBirthday: 'Sonraki Doğum Günü',
    birthdayCountdown: 'Özel दिनünüze kalan gün sayısı!',
    nextBirthdayDay: 'Hangi Gün',
    ageCategory: 'Hayat Dönemi',
    child: 'Bebek',
    boy: 'Genç',
    teenage: 'Ergen',
    adult: 'Yetişkin',
    senior: 'Altın Yaş Grubu',
    statsTitle: 'Kronolojik Öngörüler ve İstatistikler',
    faqTitle: 'Sıkça Sorulan Sorular (SSS)',
    seoDescription: 'Yaşınızı saniyesine kadar hesaplayın. Yaş dönemi avatarınızı bulun ve doğum gününe geri sayımı izleyin.',
    adsTitle: 'Destekleyici Sponsor Bağlantısı',
    adsSub: 'Ücretsiz küresel erişilebilirlik araçlarını destekler',
    adsPlaceholder: 'Google AdSense Reklam Kutusu - ID: ca-pub-99824681',
    genderMale: 'Erkek Avatarı',
    genderFemale: 'Kız Avatarı',
    genderNeutral: 'Nötr Avatar',
    genderSelect: 'Avatar Görünümünü Seçin',
    dobPlaceholder: 'Doğum tarihinizi seçin',
    analyticsTitle: 'Canlı Hesaplayıcı Katılım Platformu',
    analyticsSubtitle: 'Son 24 saatteki küresel kullanım eğilimleri',
    analyticsActiveUsers: 'Şu Anda Aktif Kullanıcı',
    analyticsTotalCalc: 'Küresel Uygulama Kullanım Endeksi',
    analyticsVoiceSuccessRate: 'Ses Çözümleyici Başarı Oranı'
  },
  ko: {
    title: '정밀 나이 계산기',
    subtitle: '초 단위의 초정밀 연령 계산, 디테일한 연대 통계 및 프리미엄 분석',
    birthDateLabel: '생년월일',
    birthTimeLabel: '태어난 시간 (선택 사항)',
    calculateBtn: '정확한 나이 계산하기',
    voiceBtnLabel: '음성 입력 지원',
    voiceListening: '생년월일을 듣고 있습니다... (예: "천구백구십오년 시월 이십일일")',
    voiceProcessing: '음성 분석을 구동 중입니다...',
    voiceError: '날짜가 명확하게 들리지 않았습니다. "년 월 일" 규칙으로 말해보세요.',
    voiceSuccess: '음성 명령을 통해 성공적으로 생년월일이 입력되었습니다!',
    voiceStopBtn: '음성 수신 중단',
    themeToggle: '테마 전환',
    languageSelect: '언어 선택',
    years: '세 (년)',
    months: '개월',
    days: '일',
    hours: '시간',
    minutes: '분',
    seconds: '초',
    weeks: '주일',
    nextBirthday: '다음 생일',
    birthdayCountdown: '당신의 특별한 기념일까지 남은 일수!',
    nextBirthdayDay: '요일',
    ageCategory: '생애 도약 단계',
    child: '영유아',
    boy: '아동/청소년',
    teenage: '청소년',
    adult: '성인',
    senior: '골든 에이지 (실버)',
    statsTitle: '연대기적 통찰 및 상세 수치',
    faqTitle: '자주 묻는 질문 (FAQ)',
    seoDescription: '초 단위까지 정밀하게 나이를 측정하세요. 각 연령대에 특화된 라이프 아바타와 다음 생일까지 남은 D-day 카운트다운을 표시합니다.',
    adsTitle: '스폰서 배너 광고',
    adsSub: '이 도구를 전 세계 전연령에 온전한 무료 서비스로 제공하는 데 기여합니다',
    adsPlaceholder: 'Google AdSense 가상 샌드박스 영역 - ID: ca-pub-99824681',
    genderMale: '남성형 아바타',
    genderFemale: '여성형 아바타',
    genderNeutral: '중립형 아바타',
    genderSelect: '원하는 아바타 성별 보기 구성',
    dobPlaceholder: '생년월일 선택',
    analyticsTitle: '실시간 분석 계산기 통합 지표',
    analyticsSubtitle: '지난 24시간 동안 전 세계에서 발생한 트렌드 통계',
    analyticsActiveUsers: '현재 접속 중인 사용자 수',
    analyticsTotalCalc: '누적 연산 인덱스 수치',
    analyticsVoiceSuccessRate: '음성 정확도 실시간 성공 기록률'
  },
  vi: {
    title: 'Bộ Tính Tuổi Chính Xác',
    subtitle: 'Tính tuổi cực kỳ chính xác, phân tích chi tiết & thống kê cao cấp',
    birthDateLabel: 'Ngày Sinh',
    birthTimeLabel: 'Giờ Sinh (Không bắt buộc)',
    calculateBtn: 'Tính Tuổi Chính Xác',
    voiceBtnLabel: 'Nhập Nhận Diện Giọng Nói',
    voiceListening: 'Đang lắng nghe ngày sinh của bạn... (Ví dụ: "hai mươi mốt tháng mười năm một chín chín lăm")',
    voiceProcessing: 'Đang chuyển đổi phân tích giọng nói...',
    voiceError: 'Không thể nhận dạng ngày một cách rõ ràng. Hãy thử nói: "Ngày Tháng Năm".',
    voiceSuccess: 'Đã nhận dạng ngày thành công từ giọng nói!',
    voiceStopBtn: 'Dừng ghi âm',
    themeToggle: 'Thay Đổi Chủ Đề',
    languageSelect: 'Chọn Ngôn Ngữ',
    years: 'Tuổi (Năm)',
    months: 'Tháng',
    days: 'Ngày',
    hours: 'Giờ',
    minutes: 'Phút',
    seconds: 'Giây',
    weeks: 'Tuần',
    nextBirthday: 'Sinh Nhật Tiếp Theo',
    birthdayCountdown: 'Số ngày còn lại cho đến ngày đặc biệt của bạn!',
    nextBirthdayDay: 'Rơi vào ngày',
    ageCategory: 'Giai Đoạn Cuộc Đời',
    child: 'Trẻ sơ sinh',
    boy: 'Thiếu nhi/Thanh niên',
    teenage: 'Thiếu niên',
    adult: 'Người trưởng thành',
    senior: 'Thành viên Vàng',
    statsTitle: 'Phân Tích Chi Tiết Theo Thời Gian',
    faqTitle: 'Câu Hỏi Thường Gặp (FAQ)',
    seoDescription: 'Tính toán chính xác tuổi của bạn đến từng giây. Tìm hình đại diện trực quan theo nhóm tuổi và đếm ngược thời gian sinh nhật.',
    adsTitle: 'Liên Kết Tài Trợ Ads',
    adsSub: 'Hỗ trợ duy trì miễn phí các công cụ hỗ trợ người dùng toàn cầu',
    adsPlaceholder: 'Sandbox Google AdSense dành cho Nhà tài trợ - ID: ca-pub-99824681',
    genderMale: 'Avatar Nam',
    genderFemale: 'Avatar Nữ',
    genderNeutral: 'Avatar Trung Tính',
    genderSelect: 'Chọn Góc Nhìn Avatar nhóm tuổi',
    dobPlaceholder: 'Chọn ngày sinh của bạn',
    analyticsTitle: 'Số Liệu Thống Kê Người Dùng Trực Tuyến',
    analyticsSubtitle: 'Xu hướng sử dụng toàn cầu trong 24 giờ qua',
    analyticsActiveUsers: 'Số người tính tuổi trực tiếp ngay lúc này',
    analyticsTotalCalc: 'Chỉ số lượt tính toán toàn cầu',
    analyticsVoiceSuccessRate: 'Tỷ lệ nhận diện giọng nói chính xác'
  },
  id: {
    title: 'Kalkulator Umur Akurat',
    subtitle: 'Penghitungan umur dengan tingkat presisi tinggi, rincian kronologis terperinci',
    birthDateLabel: 'Tanggal Lahir',
    birthTimeLabel: 'Jam Lahir (Opsional)',
    calculateBtn: 'Hitung Umur Akurat',
    voiceBtnLabel: 'Input Suara',
    voiceListening: 'Mendengarkan tanggal lahir Anda... (Contoh: "dua puluh satu oktober seribu sembilan ratus sembilan puluh lima")',
    voiceProcessing: 'Menganalisis hasil transkripsi suara...',
    voiceError: 'Gagal mendeteksi tanggal secara akurat. Coba katakan: "Tanggal Bulan Tahun".',
    voiceSuccess: 'Tanggal berhasil dimasukkan menggunakan deteksi suara!',
    voiceStopBtn: 'Hentikan Rekam Suara',
    themeToggle: 'Ganti Tema',
    languageSelect: 'Pilih Bahasa',
    years: 'Tahun',
    months: 'Bulan',
    days: 'Hari',
    hours: 'Jam',
    minutes: 'Menit',
    seconds: 'Detik',
    weeks: 'Minggu',
    nextBirthday: 'Ulang Tahun Berikutnya',
    birthdayCountdown: 'Hari tersisa menuju hari spesial Anda!',
    nextBirthdayDay: 'Jatuh pada hari',
    ageCategory: 'Fase Kehidupan',
    child: 'Balita (Anak)',
    boy: 'Remaja Muda',
    teenage: 'Remaja',
    adult: 'Dewasa',
    senior: 'Lansia Mulia',
    statsTitle: 'Wawasan Waktu Kronologis & Statistik',
    faqTitle: 'Pertanyaan Sering Diajukan (FAQ)',
    seoDescription: 'Hitung usia akurat Anda hingga hitungan detik. Temukan avatar visual Anda dan pantau hitungan mundur ulang tahun.',
    adsTitle: 'Penempatan Iklan Sponsor',
    adsSub: 'Dukung kestabilan akses gratis alat bantu aksesibilitas global',
    adsPlaceholder: 'Kotak Google AdSense Sandbox - ID: ca-pub-99824681',
    genderMale: 'Avatar Laki-laki',
    genderFemale: 'Avatar Perempuan',
    genderNeutral: 'Avatar Netral',
    genderSelect: 'Pilih Variasi Avatar Kelompok',
    dobPlaceholder: 'Pilih tanggal lahir Anda',
    analyticsTitle: 'Aktivitas Penggunaan Kalkulator Langsung',
    analyticsSubtitle: 'Tren akses global selama 24 jam terakhir',
    analyticsActiveUsers: 'Pengguna Aktif Menghitung Saat Ini',
    analyticsTotalCalc: 'Indeks Akumulasi Penggunaan Global',
    analyticsVoiceSuccessRate: 'Persentase Deteksi Pengenalan Suara'
  },
  nl: {
    title: 'Exacte Leeftijdscalculator',
    subtitle: 'Uiterst nauwkeurige leeftijdsberekening, exacte tijdsregistratie in seconden',
    birthDateLabel: 'Geboortedatum',
    birthTimeLabel: 'Tijdstip van Geboorte (Optioneel)',
    calculateBtn: 'Bereken Exacte Leeftijd',
    voiceBtnLabel: 'Spraakinvoer Datum',
    voiceListening: 'Luistert naar geboortedatum... (bijv. "eenentwintig oktober negentienvijfennegentig")',
    voiceProcessing: 'Spraakgestuurde invoer parseren...',
    voiceError: 'Datum werd niet duidelijk herkend. Spreek uit als "Dag Maand Jaar".',
    voiceSuccess: 'Geboortedatum succesvol geladen via spraakinvoer!',
    voiceStopBtn: 'Stop met Luisteren',
    themeToggle: 'Wissel Thema',
    languageSelect: 'Kies Taal',
    years: 'Jaar',
    months: 'Maanden',
    days: 'Dagen',
    hours: 'Uren',
    minutes: 'Minuten',
    seconds: 'Seconden',
    weeks: 'Weken',
    nextBirthday: 'Volgende Verjaardag',
    birthdayCountdown: 'Aantal resterende dagen tot uw speciale dag!',
    nextBirthdayDay: 'Valt op een',
    ageCategory: 'Levensfase',
    child: 'Peuter / Kind',
    boy: 'Jeugd',
    teenage: 'Tiener',
    adult: 'Volwassene',
    senior: 'Gouden Leeftijd',
    statsTitle: 'Chronologische Gegevens & Statistieken',
    faqTitle: 'Veelgestelde Vragen (FAQ)',
    seoDescription: 'Bereken uw exacte leeftijd tot op de seconde nauwkeurig. Ontdek uw levensfase avatar en countdown tot uw volgende verjaardag.',
    adsTitle: 'Gesponsorde Ad-Placement Area',
    adsSub: 'Ondersteunt gratis wereldwijde toegankelijkheidstoepassingen',
    adsPlaceholder: 'Google AdSense Sandbox Block - ID: ca-pub-99824681',
    genderMale: 'Jongens Avatar',
    genderFemale: 'Meisjes Avatar',
    genderNeutral: 'Neutrale Avatar',
    genderSelect: 'Kies Avatar Perspectief',
    dobPlaceholder: 'Selecteer uw geboortedatum',
    analyticsTitle: 'Live Calculator Engagement Platform',
    analyticsSubtitle: 'Globaal gebruik over de afgelopen 24 uur',
    analyticsActiveUsers: 'Actieve Calculators Op Dit Moment',
    analyticsTotalCalc: 'Wereldwijde Gebruiksindex',
    analyticsVoiceSuccessRate: 'Nauwkeurighedspercentage Spraakparser'
  },
  pl: {
    title: 'Dokładny Kalkulator Wieku',
    subtitle: 'Wysoka precyzja, dokładny podział czasu i ekskluzywne statystyki',
    birthDateLabel: 'Data urodzenia',
    birthTimeLabel: 'Godzina urodzenia (Opcjonalnie)',
    calculateBtn: 'Oblicz Dokładny Wiek',
    voiceBtnLabel: 'Wprowadź głosowo',
    voiceListening: 'Słucham daty urodzenia... (np. "dwudziesty pierwszy października tysiąc dziewięćset dziewięćdziesiąt piąty")',
    voiceProcessing: 'Parsowanie komendy głosowej...',
    voiceError: 'Nie udało się wyraźnie rozpoznać daty. Spróbuj wypowiedzieć "Dzień Miesiąc Rok".',
    voiceSuccess: 'Pomyślnie wczytano datę przy użyciu komendy głosowej!',
    voiceStopBtn: 'Zatrzymaj nasłuchiwanie',
    themeToggle: 'Przełącz motyw',
    languageSelect: 'Wybierz język',
    years: 'Lat',
    months: 'Miesięcy',
    days: 'Dni',
    hours: 'Godzin',
    minutes: 'Minut',
    seconds: 'Secund',
    weeks: 'Tygodni',
    nextBirthday: 'Następne Urodziny',
    birthdayCountdown: 'Dni pozostałe do Twojego wyjątkowego święta!',
    nextBirthdayDay: 'Wypada w dniu',
    ageCategory: 'Kategoria życia',
    child: 'Dziecko',
    boy: 'Młodzież / Dziecko starsze',
    teenage: 'Nastolatek',
    adult: 'Dorosły',
    senior: 'Złoty senior',
    statsTitle: 'Chronologiczne Statystyki i Raporty',
    faqTitle: 'Najczęściej Zadawane Pytania (FAQ)',
    seoDescription: 'Oblicz swój precyzyjny wiek co do sekundy. Zobacz awatar swojej grupy wiekowej i licznik czasu do urodzin.',
    adsTitle: 'Reklama Sponsorowana',
    adsSub: 'Wspiera bezpłatne globalne dostarczanie narzędzi ułatwień dostępu',
    adsPlaceholder: 'Boks demonstracyjny Google AdSense - ID: ca-pub-99824681',
    genderMale: 'Awatar Chłopca',
    genderFemale: 'Awatar Dziewczynki',
    genderNeutral: 'Awatar Neutralny',
    genderSelect: 'Wybierz styl wyświetlania awatara',
    dobPlaceholder: 'Wybierz datę urodzenia',
    analyticsTitle: 'Aktywność Kalkulatora w Czasie Rzeczywistym',
    analyticsSubtitle: 'Globalne trendy użycia w ciągu ostatnich 24 godzin',
    analyticsActiveUsers: 'Aktualnie aktywnych obliczeń',
    analyticsTotalCalc: 'Globalny indeks użycia aplikacji',
    analyticsVoiceSuccessRate: 'Wskaźnik dokładności nasłuchu'
  }
};

export const faqs: Record<LanguageCode, FAQItem[]> = {
  en: [
    {
      id: 'faq1',
      question: 'How is the precise age calculated on this platform?',
      answer: 'We compute age using real leap year cycles, counting exact months and variable calendar days (e.g. 28, 30, or 31 days) from your birth date up to the current system millisecond in your active timezone.'
    },
    {
      id: 'faq2',
      question: 'How does the voice date-of-birth command entry work?',
      answer: 'By enabling your microphone, we trigger the browser’s localized Web Speech Recognition API. Once spoken, our premium parser scans for named months, digit numbers, and year references across English, Spanish, Hindi, Bengali, Arabic, and more, instantly inputting the correct Gregorian calendar schema.'
    },
    {
      id: 'faq3',
      question: 'How are the Life Category Avatars assigned?',
      answer: 'We classify the results as: "Child" for ages under 5, "Youth" for ages 5 to 12, "Teenager" for ages 13 to 19, "Adult" for 20 to 59, and "Golden Citizen" for 60+. Avatars instantly adapt using fluid SVGs that capture responsive attributes based on selected styles.'
    },
    {
      id: 'faq4',
      question: 'Is my input date stored on any remote cloud database?',
      answer: 'No. All calculations, speech transcript parsing, and time measurements occur strictly client-side inside your browser sandbox to ensure 100% data confidentiality and private security.'
    }
  ],
  es: [
    {
      id: 'faq1',
      question: '¿Cómo se calcula la edad precisa en esta plataforma?',
      answer: 'Se calcula calculando la diferencia exacta entre su hora de nacimiento y el momento actual, considerando bisiestos y variables de días mensuales (28, 30 o 31 días) en su zona horaria activa.'
    },
    {
      id: 'faq2',
      question: '¿Cómo funciona la entrada de fecha de nacimiento por voz?',
      answer: 'Al activar el micrófono, la API de reconocimiento de voz del navegador convierte su lenguaje hablado en texto. Nuestro parser busca nombres de meses, valores de dígitos y años para rellenar la fecha automáticamente.'
    },
    {
      id: 'faq3',
      question: '¿Cómo se asignan los avatares de categoría de vida?',
      answer: 'Se definen bajo rangos: "Niño" (menores de 5), "Joven" (5-12), "Adolescente" (13-19), "Adulto" (20-59) y "Ciudadano Dorado" (60+), con un estilo vectorial vibrante y adaptativo.'
    },
    {
      id: 'faq4',
      question: '¿Se guarda mi fecha en alguna base de datos en la nube?',
      answer: 'No. Todos los procesamientos de cálculo y voz ocurren localmente en su propio navegador en un entorno seguro y de máxima privacidad.'
    }
  ],
  fr: [
    {
      id: 'faq1',
      question: 'Comment l\'âge précis est-il calculé sur ce site ?',
      answer: 'Nous calculons la différence chronologique exacte en tenant compte des années bissextiles, des longueurs variables des mois (28, 30 ou 31 jours) et du fuseau horaire actif pour un résultat scientifique parfait.'
    },
    {
      id: 'faq2',
      question: 'Comment marche l\'accessibilité d\'entrée vocale de naissance ?',
      answer: 'Nous utilisons l\'API Web Speech pour capter votre voix. Notre algorithme extrait dynamiquement le mois, le jour et l\'année de naissance pour remplir automatiquement le calendrier.'
    },
    {
      id: 'faq3',
      question: 'Comment les catégories d\'avatars réagissent-elles ?',
      answer: 'Les tranches d\'âges sont classées ainsi : Enfant (0-4), Jeune (5-12), Adolescent (13-19), Adulte (20-59) et Citoyen d\'Or (60+). Un design SVG s\'affiche selon la perspective choisie.'
    },
    {
      id: 'faq4',
      question: 'Mes informations privées sont-elles conservées sur un serveur ?',
      answer: 'Non, aucune donnée n\'est envoyée à l\'extérieur. Le fonctionnement se fait exclusivement en local au sein de l\'application à page unique.'
    }
  ],
  de: [
    {
      id: 'faq1',
      question: 'Wie wird das genaue Alter auf dieser Seite berechnet?',
      answer: 'Wir ermitteln das Alter unter Berücksichtigung von Schaltjahren, der exakten Anzahl an Monatstagen (28, 30 oder 31) und der aktuellen Echtzeit Ihres Browsers.'
    },
    {
      id: 'faq2',
      question: 'Wie funktioniert die barrierefreie Spracheingabe?',
      answer: 'Nach Aktivierung des Mikrofons wird der gesprochene Satz interpretiert. Der Algorithmus sucht nach Monatsnamen und Ziffern und überträgt das Geburtsdatum sofort ins Datumsfeld.'
    },
    {
      id: 'faq3',
      question: 'Wie sind die Lebenskategorien für Avatare aufgeteilt?',
      answer: 'Es gibt folgende Stufen: Kind (unter 5 Jahre), Jugendliche (5-12), Teenager (13-19), Erwachsener (20-59) und Seniorenklasse (60+).'
    },
    {
      id: 'faq4',
      question: 'Werden meine eingegebenen Daten auf Servern gespeichert?',
      answer: 'Nein. Alle Berechnungen und Spracherkennungsdaten finden vollständig lokal auf Ihrem Gerät statt. Absolute Privatsphäre ist garantiert.'
    }
  ],
  hi: [
    {
      id: 'faq1',
      question: 'इस प्लेटफ़ॉर्म पर सटीक उम्र कैसे गिनी जाती है?',
      answer: 'हम आपके जन्म के समय से लेकर वर्तमान क्षण तक लीप ईयर चक्र, महीनों के सटीक दिनों (२८, ३०, या ३१ दिन) और आपके टाइमज़ोन का मिलान कर सटीक उम्र की गणना करते हैं।'
    },
    {
      id: 'faq2',
      question: 'आवाज आधारित जन्म तिथि दर्ज करने की सुविधा कैसे काम करती है?',
      answer: 'आपके माइक्रोफ़ोन की अनुमति से हम ब्राउज़र की वेब स्पीच एपीआई का उपयोग करते हैं। आपके बोलने के बाद, हमारा सिस्टम महीनों के नाम और साल के अंकों को पहचानकर तिथि को स्वचालित सेट करता है।'
    },
    {
      id: 'faq3',
      question: 'लाइफ कैटेगरी अवतार का निर्धारण कैसे होता है?',
      answer: 'आयु वर्ग इस प्रकार है: ५ वर्ष से कम पर "शिशु", ५-१२ पर "बालक/बालिका", १३-१९ पर "किशोर", २०-५९ पर "वयस्क", और ६०+ होने पर "वरिष्ठ नागरिक" का वेक्टर अवतार दिखाई देता है।'
    },
    {
      id: 'faq4',
      question: 'क्या मेरी जन्मतिथि कहीं क्लाउड में सहेज कर रखी जाती है?',
      answer: 'बिल्कुल नहीं! सुरक्षा और गोपनीयता को १००% अक्षुण्ण रखने के लिए यह कैलकुलेटर पूर्णतः आपके ब्राउज़र के अंदर कार्य करता है।'
    }
  ],
  ja: [
    {
      id: 'faq1',
      question: '年齢判定はどのようなアルゴリズムで行われていますか？',
      answer: 'うるう年、各月の正確な日数（28日、30日、31日）、お使いのブラウザのアクティブタイムゾーンでの一ミリ秒単位の時間差を割り当てて高精度に実年齢を取得します。'
    },
    {
      id: 'faq2',
      question: '生年月日の音声入力機能はどのように制御していますか？',
      answer: 'マイクが有効化されるとブラウザのWeb Speech APを実行し、日本語や多言語で話された月日・数値を年齢算出用パターンにパースして即座にカレンダーにマッピングします。'
    },
    {
      id: 'faq3',
      question: '年代ごとのキャラクターアバターの基準を教えてください。',
      answer: '0〜4歳（乳幼児）、5〜12歳（児童）、13〜19歳（ティーン）、20〜59歳（大人）、60歳以上（シニア世代）に区分され、美しく滑らかに動くアバターアートワークに投影されます。'
    },
    {
      id: 'faq4',
      question: '私の誕生日情報がサーバー等に収集されるリスクはありますか？',
      answer: 'ありません。すべての計算や音声翻訳などのパース処理はクライアント（お使いのデバイス上）で完結しているため安心してご利用いただけます。'
    }
  ],
  bn: [
    {
      id: 'faq1',
      question: 'এই প্ল্যাটফর্মে কীভাবে একদম নিখুঁত বয়স হিসাব করা হচ্ছে?',
      answer: 'অধিবর্ষ (লিপ ইয়ার), মাসের নির্দিষ্ট দিনসংখ্যা (২৮, ৩০ বা ৩১ দিন) এবং জন্ম তারিখ হতে চলতি সময়ের সঠিক মিলি সেকেন্ড পর্যন্ত আপনার সক্রিয় টাইমজোন মিলিয়ে বয়স হিসাব করা হয়।'
    },
    {
      id: 'faq2',
      question: 'ভয়েস কমান্ডের মাধ্যমে জন্মদিন ইনপুট করার প্রক্রিয়াটি কী?',
      answer: 'আপনার মাইক্রোফোন সক্রিয় করার পর, আমরা ব্রাউজারের ওয়েব স্পিচ রিকগনিশন এপিআই ট্রিগার করি। আপনি যখন তারিখ বলেন, আমাদের অ্যালগরিদম বাংলা বা ইংরেজিতে বলা মাসের নাম ও বছর স্বয়ংক্রিয়ভাবে ইনপুট বক্সে লিখে দেয়।'
    },
    {
      id: 'faq3',
      question: 'কোন বয়সসীমায় কী ধরণের লাইফ ক্যাটাগরি অবতার দেখানো হয়?',
      answer: 'বয়সের ভিত্তিতে ৫ বছরের নিচে "শিশু", ৫-১২ বছর "কিশোর-কিশোরী", ১৩-১৯ বছর "তরুণ-তরুণী", ২০-৫৯ বছর "প্রাপ্তবয়স্ক" এবং ৬০ বছরের বেশি বয়সীদের সুন্দর "প্রবীণ নাগরিক" চমৎকার ভেক্টর চরিত্রে পরিবর্তন করা হয়।'
    },
    {
      id: 'faq4',
      question: 'আমার দেওয়া ব্যক্তিগত জন্ম তারিখ কি কোনো সার্ভারে জমা থাকে?',
      answer: 'না, কোনো সার্ভারে আপনার তথ্য পাঠানো হয় না। সকল হিসাব এবং ভয়েস সনাক্তকরণ শতভাগ সুরক্ষিতভাবে আপনার ব্রাউজারেই সম্পন্ন হয়।'
    }
  ],
  ar: [
    {
      id: 'faq1',
      question: 'كيف تحسب الآلة عمر دقيق للمستعلم؟',
      answer: 'نقوم بالعد المتطابق بالثواني بالرجوع لدورات الأعوام الكبيسة وعدد أيام الأشهر المتقبلة (٢٨ أو ٣٠ أو ٣١ يوماً) لكي يعطي النتيجة بدقة حيوية متطابقة تماماً.'
    },
    {
      id: 'faq2',
      question: 'كيف يتغلغل نظام الاستماع الصوتي لدخول العمر بالمنطوق؟',
      answer: 'عبر تليين الميكروفون الموجه، تباشر واجهة المستشعر تحليل المسموع كأقسام للزمن والتقويم الهجري الشمسي تلقائياً لتركيب دالة تاريخ حية دون لمس الأزرار.'
    },
    {
      id: 'faq3',
      question: 'ما هي معايير تصنيف شخصيات الأفاتار العمرية الملخصة؟',
      answer: 'العتبات مدروسة كالتالي: طفل (تحت ٥ سنوات)، يافع (٥-١٢ سنة)، مراهق (١٣-١٩ سنة)، بالغ (٢٠-٥٩ سنة)، كبار السن الموقرين (٦٠ سنة فما فوق).'
    },
    {
      id: 'faq4',
      question: 'هل يخزن خادم عن بعد معطيات مولدي وسري الديموغرافي؟',
      answer: 'لا على الإطلاق. تعمل الحاسبة حصرياً وبشكل آمن داخل بيئة متصفحك للحفاظ على خصوصيتك وسريتك بنسبة ١٠٠ بالمائة.'
    }
  ],
  pt: [
    {
      id: 'faq1',
      question: 'Como a idade precisa é calculada nesta plataforma?',
      answer: 'Calculamos a idade usando ciclos reais de anos bissextos, contando meses exatos e dias variáveis do calendário (ex: 28, 30 ou 31 dias) desde a sua data de nascimento até o milissegundo atual do sistema.'
    },
    {
      id: 'faq2',
      question: 'Como funciona o comando de voz para data de nascimento?',
      answer: 'Ao habilitar seu microfone, acionamos a API de Reconhecimento de Voz do navegador. Uma vez falado, nosso analisador verifica meses, dígitos e anos para preencher a data.'
    },
    {
      id: 'faq3',
      question: 'Como os Avatares de Categoria de Vida são atribuídos?',
      answer: 'Classificamos como: "Criança" abaixo de 5 anos, "Jovem" de 5 a 12, "Adolescente" de 13 a 19, "Adulto" de 20 a 59 e "Cidadão de Ouro" para maiores de 60 anos.'
    },
    {
      id: 'faq4',
      question: 'Minha data de nascimento é salva em algum banco de dados?',
      answer: 'Não. Todos os cálculos, análises de fala e medições de tempo ocorrem estritamente no cliente, dentro do sandbox do seu navegador, garantindo 100% de privacidade.'
    }
  ],
  ru: [
    {
      id: 'faq1',
      question: 'Как рассчитывается точный возраст на этой платформе?',
      answer: 'Мы вычисляем возраст с учетом високосных лет, подсчитывая точные месяцы и дни (например, 28, 30 или 31 день) от даты вашего рождения до текущей миллисекунды в вашем часовом поясе.'
    },
    {
      id: 'faq2',
      question: 'Как работает голосовой ввод даты рождения?',
      answer: 'Когда вы включаете микрофон, мы запускаем встроенное в браузер распознавание речи. Парсер находит названия месяцев, цифры и годы для автоматического заполнения формы.'
    },
    {
      id: 'faq3',
      question: 'Как распределяются аватары жизненного этапа?',
      answer: 'Категории следующие: «Ребенок» до 5 лет, «Молодежь» от 5 до 12 лет, «Подросток» от 13 до 19 лет, «Взрослый» от 20 до 59 лет и «Золотой возраст» от 60 лет.'
    },
    {
      id: 'faq4',
      question: 'Сохраняется ли моя дата рождения в облачной базе данных?',
      answer: 'Нет. Все вычисления, распознавание речи и замеры времени выполняются исключительно на вашем устройстве, обеспечивая полную конфиденциальность.'
    }
  ],
  zh: [
    {
      id: 'faq1',
      question: '平台是如何精准计算年龄的？',
      answer: '我们根据您出生时的具体时分秒，结合真实公历中的闰年周期、大小月天数差（如28、30、31天）进行实时高精度换算，直到浏览器当下的毫秒计数。'
    },
    {
      id: 'faq2',
      question: '语音输入出生日期的功能是如何动作的？',
      answer: '当您授权麦克风并说话时，我们调用浏览器的 Web Speech 语音接口接收声波文字，并经过算法精准匹配中文、数字、年、月、日等模式，进而自适应填入。'
    },
    {
      id: 'faq3',
      question: '人生成长阶段头像是如何划分的？',
      answer: '标准为：5岁以下归为"幼儿"，5至12岁为"儿童"，13至19岁为"少年"，20至59岁为"成年人"，60岁及以上为"金龄长者"，并配合SVG头像即时渲染。'
    },
    {
      id: 'faq4',
      question: '我的隐私生日日期数据会被上传至云端服务器中吗？',
      answer: '决不。所有年龄段计算、语音分词提取、页面生命倒计时等功能全部在本地浏览器沙箱中单向运行，无法也不具备任何后台收集特征，绝对保证安全。'
    }
  ],
  it: [
    {
      id: 'faq1',
      question: 'Come viene calcolata l\'età precisa su questa piattaforma?',
      answer: 'Calcoliamo l\'età utilizzando cicli reali di anni bisestili, contando i mesi esatti e i giorni variabili del calendario (es. 28, 30 o 31 giorni) dalla data di nascita al millisecondo corrente.'
    },
    {
      id: 'faq2',
      question: 'Come funziona l\'inserimento vocale della data di nascita?',
      answer: 'Attivando il microfono, utilizziamo l\'API Web Speech del browser. Una volta pronunciata, il nostro parser analizza mesi, cifre e anni e inserisce automaticamente la data.'
    },
    {
      id: 'faq3',
      question: 'Come vengono assegnati gli Avatar della Categoria della Vita?',
      answer: 'Classifichiamo come: "Neonato" sotto i 5 anni, "Giovane" dai 5 ai 12 anni, "Adolescente" dai 13 ai 19 anni, "Adulto" dai 20 os ai 59 anni e "Cittadino d\'Oro" dai 60 anni in su.'
    },
    {
      id: 'faq4',
      question: 'I miei dati personali vengono salvati in un database?',
      answer: 'No. Tutti i calcoli, il riconoscimento vocale e le misurazioni temporali avvengono esclusivamente a livello client nel sandboxed del browser, garantendo il 100% della privacy.'
    }
  ],
  tr: [
    {
      id: 'faq1',
      question: 'Yaş hesaplama işlemi ne düzeyde hassastır?',
      answer: 'Hesaplamamız, doğum gününüzden şu anki milisaniyeye kadar olan aralığı; artık yılları, ayların gün sayılarını (28, 30, 31 gün) dikkate alarak tam diferansiyel zaman mantığı ile yürütür.'
    },
    {
      id: 'faq2',
      question: 'Sesle doğum günü tarihi girme özelliği nasıl çalışmaktadır?',
      answer: 'Mikrofonu etkinleştirerek tarayıcınızın konuşma tanıma altyapısını kullanırız. Algılanan konuşmadaki ay adları, sayılar ve yıl bilgileri çözülerek kutucuklara yansıtılır.'
    },
    {
      id: 'faq3',
      question: 'Yaş Dönemi Avatarları neye göre belirlenmektedir?',
      answer: 'Kategoriler: 5 yaş altı "Bebek", 5-12 yaş "Genç", 13-19 yaş "Ergen", 20-59 yaş "Yetişkin" ve 60 yaş üzeri için "Altın Yaş Grubu" olarak tespit edilmiştir.'
    },
    {
      id: 'faq4',
      question: 'Doğum günü verilerim herhangi bir sunucuda tutuluyor mu?',
      answer: 'Kesinlikle hayır. Tüm ses analizleri, hesaplamalar ve geri sayım sayaçları sadece kendi cihazınızın tarayıcısında (Local) çalışır ve dışarı sızdırılmaz.'
    }
  ],
  ko: [
    {
      id: 'faq1',
      question: '이 플랫폼에서 나이는 어떻게 초단위까지 계산됩니까?',
      answer: '저희 서비스는 윤년 주기 및 각 월별 실제 일수(28일, 30일, 31일)를 철저히 감안하며, 태어난 밀리초와 브라우저 현재 기기 시각을 매칭하여 완벽한 정밀도를 보장합니다.'
    },
    {
      id: 'faq2',
      question: '음성 기반 날짜 인식은 어떻게 수행되나요?',
      answer: '마이크를 켜면 브라우저 탑재 Web Speech API를 활용해 음성 낱말을 조합합니다. 한글 월 표현 및 아라비아 숫자, 년월일 형식을 디코딩하여 설정에 정확히 연동합니다.'
    },
    {
      id: 'faq3',
      question: '생애 도약 단계 아바타 캐릭터는 어떤 조건으로 할당되나요?',
      answer: '5세 미만은 "영유아", 5~12세는 "아동/청소년", 13~19세는 "청소년", 20~59세는 "성인", 60세 이상은 "골든 에이지" 그룹으로 자동 동기화되며 각 캐릭터로 렌더링됩니다.'
    },
    {
      id: 'faq4',
      question: '제가 기재한 소중한 신상 데이터가 데이터베이스에 남나요?',
      answer: '전혀 그렇지 않습니다. 모든 소리 식별, 나이 분석 피드백, 실시간 역량 수치는 온전히 고객님의 브라우저 내에서만 실행하므로 데이터는 100% 소멸 및 안전 처리를 장담합니다.'
    }
  ],
  vi: [
    {
      id: 'faq1',
      question: 'Làm thế nào để bộ tính tuổi tính chính xác đến từng giây?',
      answer: 'Chúng tôi tính tuổi dựa trên chu kỳ năm nhuận thực tế, độ dài chính xác của từng tháng (28, 30 hoặc 31 ngày) từ thời điểm sinh của bạn cho tới mili giây hiện tại trên hệ thống.'
    },
    {
      id: 'faq2',
      question: 'Tính năng giọng nói nhập ngày sinh hoạt động như thế nào?',
      answer: 'Với việc cấp quyền mic, hệ thống kích hoạt API Nhận diện Giọng nói của trình duyệt. Trình phân tích sẽ dò các cụm tháng, số học và năm để tự động lắp đặt vào các ô chọn tương ứng.'
    },
    {
      id: 'faq3',
      question: 'Giai đoạn tuổi và avatar trực quan được chỉ định ra sao?',
      answer: 'Hệ thống chia làm các nhóm: dưới 5 tuổi là "Trẻ sơ sinh", từ 5-12 tuổi là "Thiếu nhi", từ 13-19 tuổi là "Thiếu niên", từ 20-59 tuổi là "Người trưởng thành", và từ 60 tuổi là "Thành viên Vàng".'
    },
    {
      id: 'faq4',
      question: 'Thông tin ngày sinh nhập vào có bị lưu giữ trên máy chủ không?',
      answer: 'Không. Mọi dữ liệu phân tích, xử lý giọng nói, thuật toán trừ lịch đều diễn ra cục bộ trực tiếp trên trình duyệt của riêng bạn để bảo vệ quyền riêng tư tuyệt đối.'
    }
  ],
  id: [
    {
      id: 'faq1',
      question: 'Bagaimana umur yang presisi dihitung di sistem ini?',
      answer: 'Kami mengkalkulasi umur dengan menganut siklus tahun kabisat sesungguhnya, menghitung jumlah hari per bulan secara dinamis (28, 30, atau 31 hari) sejak Anda lahir hingga milidetik saat ini.'
    },
    {
      id: 'faq2',
      question: 'Bagaimana cara kerja input suara untuk tanggal lahir?',
      answer: 'Dengan izin mikrofon, kami menggunakan Web Speech API bawaan peramban Anda. Parser kami mendeteksi sebutan bulan, angka hari, dan angka tahun untuk mengisi pilihan tanggal secara instan.'
    },
    {
      id: 'faq3',
      question: 'Bagaimana pengelompokan Fase Kehidupan dikoordinasikan?',
      answer: 'Fase ditetapkan sebagai: "Balita" di bawah 5 tahun, "Remaja Muda" usia 5-12, "Remaja" usia 13-19, "Dewasa" usia 20-59, dan "Lansia Mulia" pada usia 60 tahun ke atas.'
    },
    {
      id: 'faq4',
      question: 'Apakah tanggal lahir saya disimpan di server atau cloud?',
      answer: 'Tidak ada data yang disimpan. Seluruh analisis suara dan formula matematika umur diproses murni di perangkat/browser Anda sendiri untuk menjamin keamanan privasi mutlak.'
    }
  ],
  nl: [
    {
      id: 'faq1',
      question: 'Hoe wordt de exacte leeftijd berekend op dit platform?',
      answer: 'We berekenen de leeftijd aan de hand van echte schrikkeljaarcycli, waarbij we exacte kalendermaanden en variabele dagen (bijv. 28, 30 of 31 dagen) optellen vanaf uw geboortedatum tot de exacte actieve seconde.'
    },
    {
      id: 'faq2',
      question: 'Hoe functioneert de sterminologie spraakinvoer?',
      answer: 'Wanneer u uw microfoon inschakelt, activeren we de Web Speech Recognition API van de browser om gesproken letters om te zetten naar exacte kalendercijfers.'
    },
    {
      id: 'faq3',
      question: 'Hoe worden de Levensfase Avatars gekoppeld?',
      answer: 'De indeling is: "Peuter" voor leeftijden onder de 5, "Jeugd" voor 5 tot 12, "Tiener" voor 13 tot 19, "Volwassene" voor 20 tot 59, en "Gouden Leeftijd" voor 60 jaar en ouder.'
    },
    {
      id: 'faq4',
      question: 'Blijven mijn geboortegegevens bewaard in de cloud?',
      answer: 'Nee. Alle berekeningen, spraakanalyses en tijdmetingen vinden volledig lokaal plaats binnen de beveiligde sandbox van uw persoonlijke browser.'
    }
  ],
  pl: [
    {
      id: 'faq1',
      question: 'W jaki sposób liczony jest tak dokładny wiek?',
      answer: 'Obliczamy wiek na podstawie rzeczywistych cykli lat przestępnych, uwzględniając dokładne długości miesięcy (28, 30 lub 31 dni) od daty urodzenia aż do bieżącego ułamka sekundy.'
    },
    {
      id: 'faq2',
      question: 'Jak działa opcja głosowego wprowadzania daty urodzenia?',
      answer: 'Po wyrażeniu zgody na mikrofon, uruchamiamy wbudowane w przeglądarkę rozpoznawanie mowy Web Speech. Nasz analizator wyszukuje nazwy miesięcy i cyfry, aby samoczynnie uzupełnić formularz.'
    },
    {
      id: 'faq3',
      question: 'Na jakiej podstawie przydzielane są awatary grup wiekowych?',
      answer: 'Stosujemy podział: dziecka do lat 5, starszego dziecka do lat 12, nastolatka do lat 19, dorosłego od 20 do 59 lat oraz złotego seniora od lat 60.'
    },
    {
      id: 'faq4',
      question: 'Czy data urodzenia jest rejestrowana w jakiejś bazie danych w chmurze?',
      answer: 'Nie. Wszystkie kalkulacje, translacje mowy i pomiary stref czasowych przebiegają wyłącznie wewnątrz pamięci podręcznej przeglądarki, gwarantując prywatność.'
    }
  ]
};
